// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddDocumentationToKnowledgeBase implements add_documentation_to_knowledge_base operation.
//
// Uploads a file or reference a webpage to use as part of the shared knowledge base.
//
// Deprecated: schema marks this operation as deprecated.
//
// POST /v1/convai/knowledge-base
func (UnimplementedHandler) AddDocumentationToKnowledgeBase(ctx context.Context, req OptBodyAddToKnowledgeBaseV1ConvaiKnowledgeBasePostMultipart, params AddDocumentationToKnowledgeBaseParams) (r AddDocumentationToKnowledgeBaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddFromFile implements add_from_file operation.
//
// Creates a new pronunciation dictionary from a lexicon .PLS file.
//
// POST /v1/pronunciation-dictionaries/add-from-file
func (UnimplementedHandler) AddFromFile(ctx context.Context, req *BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostMultipart, params AddFromFileParams) (r AddFromFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddLanguage implements add_language operation.
//
// Adds the given ElevenLab Turbo V2/V2.5 language code to the resource. Does not automatically
// generate transcripts/translations/audio.
//
// POST /v1/dubbing/resource/{dubbing_id}/language
func (UnimplementedHandler) AddLanguage(ctx context.Context, req *BodyAddALanguageToTheResourceV1DubbingResourceDubbingIDLanguagePost, params AddLanguageParams) (r AddLanguageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddMember implements add_member operation.
//
// Adds a member of your workspace to the specified group. This endpoint may only be called by
// workspace administrators.
//
// POST /v1/workspace/groups/{group_id}/members
func (UnimplementedHandler) AddMember(ctx context.Context, req *BodyAddMemberToUserGroupV1WorkspaceGroupsGroupIDMembersPost, params AddMemberParams) (r AddMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddProject implements add_project operation.
//
// Creates a new Studio project, it can be either initialized as blank, from a document or from a URL.
//
// POST /v1/studio/projects
func (UnimplementedHandler) AddProject(ctx context.Context, req *BodyCreateStudioProjectV1StudioProjectsPostMultipart, params AddProjectParams) (r AddProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddPvcVoiceSamples implements add_pvc_voice_samples operation.
//
// Add audio samples to a PVC voice.
//
// POST /v1/voices/pvc/{voice_id}/samples
func (UnimplementedHandler) AddPvcVoiceSamples(ctx context.Context, req *BodyAddSamplesToPVCVoiceV1VoicesPvcVoiceIDSamplesPostMultipart, params AddPvcVoiceSamplesParams) (r AddPvcVoiceSamplesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddSharingVoice implements add_sharing_voice operation.
//
// Add a shared voice to your collection of voices.
//
// POST /v1/voices/add/{public_user_id}/{voice_id}
func (UnimplementedHandler) AddSharingVoice(ctx context.Context, req *BodyAddSharedVoiceV1VoicesAddPublicUserIDVoiceIDPost, params AddSharingVoiceParams) (r AddSharingVoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddVoice implements add_voice operation.
//
// Add a new voice to your collection of voices in VoiceLab.
//
// POST /v1/voices/add
func (UnimplementedHandler) AddVoice(ctx context.Context, req *BodyAddVoiceV1VoicesAddPostMultipart, params AddVoiceParams) (r AddVoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AudioIsolation implements audio_isolation operation.
//
// Removes background noise from audio.
//
// POST /v1/audio-isolation
func (UnimplementedHandler) AudioIsolation(ctx context.Context, req *BodyAudioIsolationV1AudioIsolationPostMultipart, params AudioIsolationParams) (r AudioIsolationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AudioIsolationStream implements audio_isolation_stream operation.
//
// Removes background noise from audio and streams the result.
//
// POST /v1/audio-isolation/stream
func (UnimplementedHandler) AudioIsolationStream(ctx context.Context, req *BodyAudioIsolationStreamV1AudioIsolationStreamPostMultipart, params AudioIsolationStreamParams) (r AudioIsolationStreamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AudioNativeProjectUpdateContentEndpoint implements audio_native_project_update_content_endpoint operation.
//
// Updates content for the specific AudioNative Project.
//
// POST /v1/audio-native/{project_id}/content
func (UnimplementedHandler) AudioNativeProjectUpdateContentEndpoint(ctx context.Context, req OptBodyUpdateAudioNativeProjectContentV1AudioNativeProjectIDContentPostMultipart, params AudioNativeProjectUpdateContentEndpointParams) (r AudioNativeProjectUpdateContentEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelBatchCall implements cancel_batch_call operation.
//
// Cancel a running batch call and set all recipients to cancelled status.
//
// POST /v1/convai/batch-calling/{batch_id}/cancel
func (UnimplementedHandler) CancelBatchCall(ctx context.Context, params CancelBatchCallParams) (r CancelBatchCallRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ComposeDetailed implements compose_detailed operation.
//
// Compose a song from a prompt or a composition plan.
//
// POST /v1/music/detailed
func (UnimplementedHandler) ComposeDetailed(ctx context.Context, req OptBodyComposeMusicWithADetailedResponseV1MusicDetailedPost, params ComposeDetailedParams) (r ComposeDetailedRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ComposePlan implements compose_plan operation.
//
// Generate a composition plan from a prompt.
//
// POST /v1/music/plan
func (UnimplementedHandler) ComposePlan(ctx context.Context, req *BodyGenerateCompositionPlanV1MusicPlanPost, params ComposePlanParams) (r ComposePlanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ConvertChapterEndpoint implements convert_chapter_endpoint operation.
//
// Starts conversion of a specific chapter.
//
// POST /v1/studio/projects/{project_id}/chapters/{chapter_id}/convert
func (UnimplementedHandler) ConvertChapterEndpoint(ctx context.Context, params ConvertChapterEndpointParams) (r ConvertChapterEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ConvertProjectEndpoint implements convert_project_endpoint operation.
//
// Starts conversion of a Studio project and all of its chapters.
//
// POST /v1/studio/projects/{project_id}/convert
func (UnimplementedHandler) ConvertProjectEndpoint(ctx context.Context, params ConvertProjectEndpointParams) (r ConvertProjectEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAgentResponseTestRoute implements create_agent_response_test_route operation.
//
// Creates a new agent response test.
//
// POST /v1/convai/agent-testing/create
func (UnimplementedHandler) CreateAgentResponseTestRoute(ctx context.Context, req *CreateUnitTestRequest, params CreateAgentResponseTestRouteParams) (r CreateAgentResponseTestRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAudioNativeProject implements create_audio_native_project operation.
//
// Creates Audio Native enabled project, optionally starts conversion and returns project ID and
// embeddable HTML snippet.
//
// POST /v1/audio-native
func (UnimplementedHandler) CreateAudioNativeProject(ctx context.Context, req *BodyCreatesAudioNativeEnabledProjectV1AudioNativePostMultipart, params CreateAudioNativeProjectParams) (r CreateAudioNativeProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateBatchCall implements create_batch_call operation.
//
// Submit a batch call request to schedule calls for multiple recipients.
//
// POST /v1/convai/batch-calling/submit
func (UnimplementedHandler) CreateBatchCall(ctx context.Context, req *BodySubmitABatchCallRequestV1ConvaiBatchCallingSubmitPost, params CreateBatchCallParams) (r CreateBatchCallRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateClip implements create_clip operation.
//
// Creates a new segment in dubbing resource with a start and end time for the speaker in every
// available language. Does not automatically generate transcripts/translations/audio.
//
// POST /v1/dubbing/resource/{dubbing_id}/speaker/{speaker_id}/segment
func (UnimplementedHandler) CreateClip(ctx context.Context, req *SegmentCreatePayload, params CreateClipParams) (r CreateClipRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDubbing implements create_dubbing operation.
//
// Dubs a provided audio or video file into given language.
//
// POST /v1/dubbing
func (UnimplementedHandler) CreateDubbing(ctx context.Context, req OptBodyDubAVideoOrAnAudioFileV1DubbingPostMultipart, params CreateDubbingParams) (r CreateDubbingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFileDocumentRoute implements create_file_document_route operation.
//
// Create a knowledge base document generated form the uploaded file.
//
// POST /v1/convai/knowledge-base/file
func (UnimplementedHandler) CreateFileDocumentRoute(ctx context.Context, req *BodyCreateFileDocumentV1ConvaiKnowledgeBaseFilePostMultipart, params CreateFileDocumentRouteParams) (r CreateFileDocumentRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePvcVoice implements create_pvc_voice operation.
//
// Creates a new PVC voice with metadata but no samples.
//
// POST /v1/voices/pvc
func (UnimplementedHandler) CreatePvcVoice(ctx context.Context, req *BodyCreatePVCVoiceV1VoicesPvcPost, params CreatePvcVoiceParams) (r CreatePvcVoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSecretRoute implements create_secret_route operation.
//
// Create a new secret for the workspace.
//
// POST /v1/convai/secrets
func (UnimplementedHandler) CreateSecretRoute(ctx context.Context, req *PostWorkspaceSecretRequest, params CreateSecretRouteParams) (r CreateSecretRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateServiceAccountAPIKey implements create_service_account_api_key operation.
//
// Create a new API key for a service account.
//
// POST /v1/service-accounts/{service_account_user_id}/api-keys
func (UnimplementedHandler) CreateServiceAccountAPIKey(ctx context.Context, req *BodyCreateServiceAccountAPIKeyV1ServiceAccountsServiceAccountUserIDAPIKeysPost, params CreateServiceAccountAPIKeyParams) (r CreateServiceAccountAPIKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSpeaker implements create_speaker operation.
//
// Create A New Speaker.
//
// POST /v1/dubbing/resource/{dubbing_id}/speaker
func (UnimplementedHandler) CreateSpeaker(ctx context.Context, req OptBodyCreateANewSpeakerV1DubbingResourceDubbingIDSpeakerPost, params CreateSpeakerParams) (r CreateSpeakerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTextDocumentRoute implements create_text_document_route operation.
//
// Create a knowledge base document containing the provided text.
//
// POST /v1/convai/knowledge-base/text
func (UnimplementedHandler) CreateTextDocumentRoute(ctx context.Context, req *BodyCreateTextDocumentV1ConvaiKnowledgeBaseTextPost, params CreateTextDocumentRouteParams) (r CreateTextDocumentRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateURLDocumentRoute implements create_url_document_route operation.
//
// Create a knowledge base document generated by scraping the given webpage.
//
// POST /v1/convai/knowledge-base/url
func (UnimplementedHandler) CreateURLDocumentRoute(ctx context.Context, req *BodyCreateURLDocumentV1ConvaiKnowledgeBaseURLPost, params CreateURLDocumentRouteParams) (r CreateURLDocumentRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateVoice implements create_voice operation.
//
// Create a voice from previously generated voice preview. This endpoint should be called after you
// fetched a generated_voice_id using POST /v1/text-to-voice/design or POST
// /v1/text-to-voice/:voice_id/remix.
//
// POST /v1/text-to-voice
func (UnimplementedHandler) CreateVoice(ctx context.Context, req *BodyCreateANewVoiceFromVoicePreviewV1TextToVoicePost, params CreateVoiceParams) (r CreateVoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateVoiceOld implements create_voice_old operation.
//
// Create a previously generated voice. This endpoint should be called after you fetched a
// generated_voice_id using /v1/voice-generation/generate-voice.
//
// POST /v1/voice-generation/create-voice
func (UnimplementedHandler) CreateVoiceOld(ctx context.Context, req *BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost, params CreateVoiceOldParams) (r CreateVoiceOldRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWorkspaceWebhookRoute implements create_workspace_webhook_route operation.
//
// Create a new webhook for the workspace with the specified authentication type.
//
// POST /v1/workspace/webhooks
func (UnimplementedHandler) CreateWorkspaceWebhookRoute(ctx context.Context, req *BodyCreateWorkspaceWebhookV1WorkspaceWebhooksPost, params CreateWorkspaceWebhookRouteParams) (r CreateWorkspaceWebhookRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAgentRoute implements delete_agent_route operation.
//
// Delete an agent.
//
// DELETE /v1/convai/agents/{agent_id}
func (UnimplementedHandler) DeleteAgentRoute(ctx context.Context, params DeleteAgentRouteParams) (r DeleteAgentRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteChapterEndpoint implements delete_chapter_endpoint operation.
//
// Deletes a chapter.
//
// DELETE /v1/studio/projects/{project_id}/chapters/{chapter_id}
func (UnimplementedHandler) DeleteChapterEndpoint(ctx context.Context, params DeleteChapterEndpointParams) (r DeleteChapterEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteChatResponseTestRoute implements delete_chat_response_test_route operation.
//
// Deletes an agent response test by ID.
//
// DELETE /v1/convai/agent-testing/{test_id}
func (UnimplementedHandler) DeleteChatResponseTestRoute(ctx context.Context, params DeleteChatResponseTestRouteParams) (r DeleteChatResponseTestRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteConversationRoute implements delete_conversation_route operation.
//
// Delete a particular conversation.
//
// DELETE /v1/convai/conversations/{conversation_id}
func (UnimplementedHandler) DeleteConversationRoute(ctx context.Context, params DeleteConversationRouteParams) (r DeleteConversationRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDubbing implements delete_dubbing operation.
//
// Deletes a dubbing project.
//
// DELETE /v1/dubbing/{dubbing_id}
func (UnimplementedHandler) DeleteDubbing(ctx context.Context, params DeleteDubbingParams) (r DeleteDubbingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteInvite implements delete_invite operation.
//
// Invalidates an existing email invitation. The invitation will still show up in the inbox it has
// been delivered to, but activating it to join the workspace won't work. This endpoint may only be
// called by workspace administrators.
//
// DELETE /v1/workspace/invites
func (UnimplementedHandler) DeleteInvite(ctx context.Context, req *BodyDeleteExistingInvitationV1WorkspaceInvitesDelete, params DeleteInviteParams) (r DeleteInviteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteKnowledgeBaseDocument implements delete_knowledge_base_document operation.
//
// Delete a document from the knowledge base.
//
// DELETE /v1/convai/knowledge-base/{documentation_id}
func (UnimplementedHandler) DeleteKnowledgeBaseDocument(ctx context.Context, params DeleteKnowledgeBaseDocumentParams) (r DeleteKnowledgeBaseDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMcpServerRoute implements delete_mcp_server_route operation.
//
// Delete a specific MCP server configuration from the workspace.
//
// DELETE /v1/convai/mcp-servers/{mcp_server_id}
func (UnimplementedHandler) DeleteMcpServerRoute(ctx context.Context, params DeleteMcpServerRouteParams) (r DeleteMcpServerRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePhoneNumberRoute implements delete_phone_number_route operation.
//
// Delete Phone Number by ID.
//
// DELETE /v1/convai/phone-numbers/{phone_number_id}
func (UnimplementedHandler) DeletePhoneNumberRoute(ctx context.Context, params DeletePhoneNumberRouteParams) (r DeletePhoneNumberRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteProject implements delete_project operation.
//
// Deletes a Studio project.
//
// DELETE /v1/studio/projects/{project_id}
func (UnimplementedHandler) DeleteProject(ctx context.Context, params DeleteProjectParams) (r DeleteProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePvcVoiceSample implements delete_pvc_voice_sample operation.
//
// Delete a sample from a PVC voice.
//
// DELETE /v1/voices/pvc/{voice_id}/samples/{sample_id}
func (UnimplementedHandler) DeletePvcVoiceSample(ctx context.Context, params DeletePvcVoiceSampleParams) (r DeletePvcVoiceSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteRagIndex implements delete_rag_index operation.
//
// Delete RAG index for the knowledgebase document.
//
// DELETE /v1/convai/knowledge-base/{documentation_id}/rag-index/{rag_index_id}
func (UnimplementedHandler) DeleteRagIndex(ctx context.Context, params DeleteRagIndexParams) (r DeleteRagIndexRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSample implements delete_sample operation.
//
// Removes a sample by its ID.
//
// DELETE /v1/voices/{voice_id}/samples/{sample_id}
func (UnimplementedHandler) DeleteSample(ctx context.Context, params DeleteSampleParams) (r DeleteSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSecretRoute implements delete_secret_route operation.
//
// Delete a workspace secret if it's not in use.
//
// DELETE /v1/convai/secrets/{secret_id}
func (UnimplementedHandler) DeleteSecretRoute(ctx context.Context, params DeleteSecretRouteParams) (r DeleteSecretRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSegment implements delete_segment operation.
//
// Deletes a single segment from the dubbing.
//
// DELETE /v1/dubbing/resource/{dubbing_id}/segment/{segment_id}
func (UnimplementedHandler) DeleteSegment(ctx context.Context, params DeleteSegmentParams) (r DeleteSegmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteServiceAccountAPIKey implements delete_service_account_api_key operation.
//
// Delete an existing API key for a service account.
//
// DELETE /v1/service-accounts/{service_account_user_id}/api-keys/{api_key_id}
func (UnimplementedHandler) DeleteServiceAccountAPIKey(ctx context.Context, params DeleteServiceAccountAPIKeyParams) (r DeleteServiceAccountAPIKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSpeechHistoryItem implements delete_speech_history_item operation.
//
// Delete a history item by its ID.
//
// DELETE /v1/history/{history_item_id}
func (UnimplementedHandler) DeleteSpeechHistoryItem(ctx context.Context, params DeleteSpeechHistoryItemParams) (r DeleteSpeechHistoryItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteToolRoute implements delete_tool_route operation.
//
// Delete tool from the workspace.
//
// DELETE /v1/convai/tools/{tool_id}
func (UnimplementedHandler) DeleteToolRoute(ctx context.Context, params DeleteToolRouteParams) (r DeleteToolRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTranscriptByID implements delete_transcript_by_id operation.
//
// Delete a previously generated transcript by its ID.
//
// DELETE /v1/speech-to-text/transcripts/{transcription_id}
func (UnimplementedHandler) DeleteTranscriptByID(ctx context.Context, params DeleteTranscriptByIDParams) (r DeleteTranscriptByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteVoice implements delete_voice operation.
//
// Deletes a voice by its ID.
//
// DELETE /v1/voices/{voice_id}
func (UnimplementedHandler) DeleteVoice(ctx context.Context, params DeleteVoiceParams) (r DeleteVoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWhatsappAccount implements delete_whatsapp_account operation.
//
// Delete a WhatsApp account.
//
// DELETE /v1/convai/whatsapp-accounts/{phone_number_id}
func (UnimplementedHandler) DeleteWhatsappAccount(ctx context.Context, params DeleteWhatsappAccountParams) (r DeleteWhatsappAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWorkspaceWebhookRoute implements delete_workspace_webhook_route operation.
//
// Delete the specified workspace webhook.
//
// DELETE /v1/workspace/webhooks/{webhook_id}
func (UnimplementedHandler) DeleteWorkspaceWebhookRoute(ctx context.Context, params DeleteWorkspaceWebhookRouteParams) (r DeleteWorkspaceWebhookRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DownloadSpeechHistoryItems implements download_speech_history_items operation.
//
// Download one or more history items. If one history item ID is provided, we will return a single
// audio file. If more than one history item IDs are provided, we will provide the history items
// packed into a .zip file.
//
// POST /v1/history/download
func (UnimplementedHandler) DownloadSpeechHistoryItems(ctx context.Context, req *BodyDownloadHistoryItemsV1HistoryDownloadPost, params DownloadSpeechHistoryItemsParams) (r DownloadSpeechHistoryItemsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Dub implements dub operation.
//
// Regenerate the dubs for either the entire resource or the specified segments/languages. Will
// automatically transcribe and translate any missing transcriptions and translations.
//
// POST /v1/dubbing/resource/{dubbing_id}/dub
func (UnimplementedHandler) Dub(ctx context.Context, req *BodyDubsAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIDDubPost, params DubParams) (r DubRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DuplicateAgentRoute implements duplicate_agent_route operation.
//
// Create a new agent by duplicating an existing one.
//
// POST /v1/convai/agents/{agent_id}/duplicate
func (UnimplementedHandler) DuplicateAgentRoute(ctx context.Context, req OptBodyDuplicateAgentV1ConvaiAgentsAgentIDDuplicatePost, params DuplicateAgentRouteParams) (r DuplicateAgentRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditProject implements edit_project operation.
//
// Updates the specified Studio project by setting the values of the parameters passed.
//
// POST /v1/studio/projects/{project_id}
func (UnimplementedHandler) EditProject(ctx context.Context, req *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost, params EditProjectParams) (r EditProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditProjectContent implements edit_project_content operation.
//
// Updates Studio project content.
//
// POST /v1/studio/projects/{project_id}/content
func (UnimplementedHandler) EditProjectContent(ctx context.Context, req OptBodyUpdateStudioProjectContentV1StudioProjectsProjectIDContentPostMultipart, params EditProjectContentParams) (r EditProjectContentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditPvcVoice implements edit_pvc_voice operation.
//
// Edit PVC voice metadata.
//
// POST /v1/voices/pvc/{voice_id}
func (UnimplementedHandler) EditPvcVoice(ctx context.Context, req OptBodyEditPVCVoiceV1VoicesPvcVoiceIDPost, params EditPvcVoiceParams) (r EditPvcVoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditPvcVoiceSample implements edit_pvc_voice_sample operation.
//
// Update a PVC voice sample - apply noise removal, select speaker, change trim times or file name.
//
// POST /v1/voices/pvc/{voice_id}/samples/{sample_id}
func (UnimplementedHandler) EditPvcVoiceSample(ctx context.Context, req OptBodyUpdatePVCVoiceSampleV1VoicesPvcVoiceIDSamplesSampleIDPost, params EditPvcVoiceSampleParams) (r EditPvcVoiceSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditServiceAccountAPIKey implements edit_service_account_api_key operation.
//
// Update an existing API key for a service account.
//
// PATCH /v1/service-accounts/{service_account_user_id}/api-keys/{api_key_id}
func (UnimplementedHandler) EditServiceAccountAPIKey(ctx context.Context, req *BodyEditServiceAccountAPIKeyV1ServiceAccountsServiceAccountUserIDAPIKeysAPIKeyIDPatch, params EditServiceAccountAPIKeyParams) (r EditServiceAccountAPIKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditVoice implements edit_voice operation.
//
// Edit a voice created by you.
//
// POST /v1/voices/{voice_id}/edit
func (UnimplementedHandler) EditVoice(ctx context.Context, req *BodyEditVoiceV1VoicesVoiceIDEditPostMultipart, params EditVoiceParams) (r EditVoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditVoiceSettings implements edit_voice_settings operation.
//
// Edit your settings for a specific voice. "similarity_boost" corresponds to "Clarity + Similarity
// Enhancement" in the web app and "stability" corresponds to "Stability" slider in the web app.
//
// POST /v1/voices/{voice_id}/settings/edit
func (UnimplementedHandler) EditVoiceSettings(ctx context.Context, req *VoiceSettingsResponseModel, params EditVoiceSettingsParams) (r EditVoiceSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditWorkspaceWebhookRoute implements edit_workspace_webhook_route operation.
//
// Update the specified workspace webhook.
//
// PATCH /v1/workspace/webhooks/{webhook_id}
func (UnimplementedHandler) EditWorkspaceWebhookRoute(ctx context.Context, req *BodyUpdateWorkspaceWebhookV1WorkspaceWebhooksWebhookIDPatch, params EditWorkspaceWebhookRouteParams) (r EditWorkspaceWebhookRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ForcedAlignment implements forced_alignment operation.
//
// Force align an audio file to text. Use this endpoint to get the timing information for each
// character and word in an audio file based on a provided text transcript.
//
// POST /v1/forced-alignment
func (UnimplementedHandler) ForcedAlignment(ctx context.Context, req *BodyCreateForcedAlignmentV1ForcedAlignmentPostMultipart, params ForcedAlignmentParams) (r ForcedAlignmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Generate implements generate operation.
//
// Compose a song from a prompt or a composition plan.
//
// POST /v1/music
func (UnimplementedHandler) Generate(ctx context.Context, req OptBodyComposeMusicV1MusicPost, params GenerateParams) (r GenerateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateRandomVoice implements generate_random_voice operation.
//
// Generate a random voice based on parameters. This method returns a generated_voice_id in the
// response header, and a sample of the voice in the body. If you like the generated voice call
// /v1/voice-generation/create-voice with the generated_voice_id to create the voice.
//
// POST /v1/voice-generation/generate-voice
func (UnimplementedHandler) GenerateRandomVoice(ctx context.Context, req *BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost, params GenerateRandomVoiceParams) (r GenerateRandomVoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentKnowledgeBaseSize implements get_agent_knowledge_base_size operation.
//
// Returns the number of pages in the agent's knowledge base.
//
// GET /v1/convai/agent/{agent_id}/knowledge-base/size
func (UnimplementedHandler) GetAgentKnowledgeBaseSize(ctx context.Context, params GetAgentKnowledgeBaseSizeParams) (r GetAgentKnowledgeBaseSizeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentKnowledgeBaseSummariesRoute implements get_agent_knowledge_base_summaries_route operation.
//
// Gets multiple knowledge base document summaries by their IDs.
//
// GET /v1/convai/knowledge-base/summaries
func (UnimplementedHandler) GetAgentKnowledgeBaseSummariesRoute(ctx context.Context, params GetAgentKnowledgeBaseSummariesRouteParams) (r GetAgentKnowledgeBaseSummariesRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentLinkRoute implements get_agent_link_route operation.
//
// Get the current link used to share the agent with others.
//
// GET /v1/convai/agents/{agent_id}/link
func (UnimplementedHandler) GetAgentLinkRoute(ctx context.Context, params GetAgentLinkRouteParams) (r GetAgentLinkRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentLlmExpectedCostCalculation implements get_agent_llm_expected_cost_calculation operation.
//
// Calculates expected number of LLM tokens needed for the specified agent.
//
// POST /v1/convai/agent/{agent_id}/llm-usage/calculate
func (UnimplementedHandler) GetAgentLlmExpectedCostCalculation(ctx context.Context, req *LLMUsageCalculatorRequestModel, params GetAgentLlmExpectedCostCalculationParams) (r GetAgentLlmExpectedCostCalculationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentResponseTestRoute implements get_agent_response_test_route operation.
//
// Gets an agent response test by ID.
//
// GET /v1/convai/agent-testing/{test_id}
func (UnimplementedHandler) GetAgentResponseTestRoute(ctx context.Context, params GetAgentResponseTestRouteParams) (r GetAgentResponseTestRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentResponseTestsSummariesRoute implements get_agent_response_tests_summaries_route operation.
//
// Gets multiple agent response tests by their IDs. Returns a dictionary mapping test IDs to test
// summaries.
//
// POST /v1/convai/agent-testing/summaries
func (UnimplementedHandler) GetAgentResponseTestsSummariesRoute(ctx context.Context, req *ListTestsByIdsRequestModel, params GetAgentResponseTestsSummariesRouteParams) (r GetAgentResponseTestsSummariesRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentsRoute implements get_agents_route operation.
//
// Returns a list of your agents and their metadata.
//
// GET /v1/convai/agents
func (UnimplementedHandler) GetAgentsRoute(ctx context.Context, params GetAgentsRouteParams) (r GetAgentsRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAudioFromSample implements get_audio_from_sample operation.
//
// Returns the audio corresponding to a sample attached to a voice.
//
// GET /v1/voices/{voice_id}/samples/{sample_id}/audio
func (UnimplementedHandler) GetAudioFromSample(ctx context.Context, params GetAudioFromSampleParams) (r GetAudioFromSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAudioFullFromSpeechHistoryItem implements get_audio_full_from_speech_history_item operation.
//
// Returns the audio of an history item.
//
// GET /v1/history/{history_item_id}/audio
func (UnimplementedHandler) GetAudioFullFromSpeechHistoryItem(ctx context.Context, params GetAudioFullFromSpeechHistoryItemParams) (r GetAudioFullFromSpeechHistoryItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAudioNativeProjectSettingsEndpoint implements get_audio_native_project_settings_endpoint operation.
//
// Get player settings for the specific project.
//
// GET /v1/audio-native/{project_id}/settings
func (UnimplementedHandler) GetAudioNativeProjectSettingsEndpoint(ctx context.Context, params GetAudioNativeProjectSettingsEndpointParams) (r GetAudioNativeProjectSettingsEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBatchCall implements get_batch_call operation.
//
// Get detailed information about a batch call including all recipients.
//
// GET /v1/convai/batch-calling/{batch_id}
func (UnimplementedHandler) GetBatchCall(ctx context.Context, params GetBatchCallParams) (r GetBatchCallRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChapterSnapshotEndpoint implements get_chapter_snapshot_endpoint operation.
//
// Returns the chapter snapshot.
//
// GET /v1/studio/projects/{project_id}/chapters/{chapter_id}/snapshots/{chapter_snapshot_id}
func (UnimplementedHandler) GetChapterSnapshotEndpoint(ctx context.Context, params GetChapterSnapshotEndpointParams) (r GetChapterSnapshotEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChapterSnapshots implements get_chapter_snapshots operation.
//
// Gets information about all the snapshots of a chapter. Each snapshot can be downloaded as audio.
// Whenever a chapter is converted a snapshot will automatically be created.
//
// GET /v1/studio/projects/{project_id}/chapters/{chapter_id}/snapshots
func (UnimplementedHandler) GetChapterSnapshots(ctx context.Context, params GetChapterSnapshotsParams) (r GetChapterSnapshotsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChapters implements get_chapters operation.
//
// Returns a list of a Studio project's chapters.
//
// GET /v1/studio/projects/{project_id}/chapters
func (UnimplementedHandler) GetChapters(ctx context.Context, params GetChaptersParams) (r GetChaptersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConversationAudioRoute implements get_conversation_audio_route operation.
//
// Get the audio recording of a particular conversation.
//
// GET /v1/convai/conversations/{conversation_id}/audio
func (UnimplementedHandler) GetConversationAudioRoute(ctx context.Context, params GetConversationAudioRouteParams) (r GetConversationAudioRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConversationHistoriesRoute implements get_conversation_histories_route operation.
//
// Get all conversations of agents that user owns. With option to restrict to a specific agent.
//
// GET /v1/convai/conversations
func (UnimplementedHandler) GetConversationHistoriesRoute(ctx context.Context, params GetConversationHistoriesRouteParams) (r GetConversationHistoriesRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConversationHistoryRoute implements get_conversation_history_route operation.
//
// Get the details of a particular conversation.
//
// GET /v1/convai/conversations/{conversation_id}
func (UnimplementedHandler) GetConversationHistoryRoute(ctx context.Context, params GetConversationHistoryRouteParams) (r GetConversationHistoryRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConversationSignedLink implements get_conversation_signed_link operation.
//
// Get a signed url to start a conversation with an agent with an agent that requires authorization.
//
// GET /v1/convai/conversation/get-signed-url
func (UnimplementedHandler) GetConversationSignedLink(ctx context.Context, params GetConversationSignedLinkParams) (r GetConversationSignedLinkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDashboardSettingsRoute implements get_dashboard_settings_route operation.
//
// Retrieve Convai dashboard settings for the workspace.
//
// GET /v1/convai/settings/dashboard
func (UnimplementedHandler) GetDashboardSettingsRoute(ctx context.Context, params GetDashboardSettingsRouteParams) (r GetDashboardSettingsRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocumentationChunkFromKnowledgeBase implements get_documentation_chunk_from_knowledge_base operation.
//
// Get details about a specific documentation part used by RAG.
//
// GET /v1/convai/knowledge-base/{documentation_id}/chunk/{chunk_id}
func (UnimplementedHandler) GetDocumentationChunkFromKnowledgeBase(ctx context.Context, params GetDocumentationChunkFromKnowledgeBaseParams) (r GetDocumentationChunkFromKnowledgeBaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocumentationFromKnowledgeBase implements get_documentation_from_knowledge_base operation.
//
// Get details about a specific documentation making up the agent's knowledge base.
//
// GET /v1/convai/knowledge-base/{documentation_id}
func (UnimplementedHandler) GetDocumentationFromKnowledgeBase(ctx context.Context, params GetDocumentationFromKnowledgeBaseParams) (r GetDocumentationFromKnowledgeBaseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDubbedFile implements get_dubbed_file operation.
//
// Returns dub as a streamed MP3 or MP4 file. If this dub has been edited using Dubbing Studio you
// need to use the resource render endpoint as this endpoint only returns the original automatic dub
// result.
//
// GET /v1/dubbing/{dubbing_id}/audio/{language_code}
func (UnimplementedHandler) GetDubbedFile(ctx context.Context, params GetDubbedFileParams) (r GetDubbedFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDubbedMetadata implements get_dubbed_metadata operation.
//
// Returns metadata about a dubbing project, including whether it's still in progress or not.
//
// GET /v1/dubbing/{dubbing_id}
func (UnimplementedHandler) GetDubbedMetadata(ctx context.Context, params GetDubbedMetadataParams) (r GetDubbedMetadataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDubbedTranscriptFile implements get_dubbed_transcript_file operation.
//
// Returns transcript for the dub as an SRT or WEBVTT file.
//
// GET /v1/dubbing/{dubbing_id}/transcript/{language_code}
func (UnimplementedHandler) GetDubbedTranscriptFile(ctx context.Context, params GetDubbedTranscriptFileParams) (r GetDubbedTranscriptFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDubbingResource implements get_dubbing_resource operation.
//
// Given a dubbing ID generated from the '/v1/dubbing' endpoint with studio enabled, returns the
// dubbing resource.
//
// GET /v1/dubbing/resource/{dubbing_id}
func (UnimplementedHandler) GetDubbingResource(ctx context.Context, params GetDubbingResourceParams) (r GetDubbingResourceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGenerateVoiceParameters implements get_generate_voice_parameters operation.
//
// Get possible parameters for the /v1/voice-generation/generate-voice endpoint.
//
// GET /v1/voice-generation/generate-voice/parameters
func (UnimplementedHandler) GetGenerateVoiceParameters(ctx context.Context) (r *VoiceGenerationParameterResponseModel, _ error) {
	return r, ht.ErrNotImplemented
}

// GetKnowledgeBaseContent implements get_knowledge_base_content operation.
//
// Get the entire content of a document from the knowledge base.
//
// GET /v1/convai/knowledge-base/{documentation_id}/content
func (UnimplementedHandler) GetKnowledgeBaseContent(ctx context.Context, params GetKnowledgeBaseContentParams) (r GetKnowledgeBaseContentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetKnowledgeBaseDependentAgents implements get_knowledge_base_dependent_agents operation.
//
// Get a list of agents depending on this knowledge base document.
//
// GET /v1/convai/knowledge-base/{documentation_id}/dependent-agents
func (UnimplementedHandler) GetKnowledgeBaseDependentAgents(ctx context.Context, params GetKnowledgeBaseDependentAgentsParams) (r GetKnowledgeBaseDependentAgentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetKnowledgeBaseListRoute implements get_knowledge_base_list_route operation.
//
// Get a list of available knowledge base documents.
//
// GET /v1/convai/knowledge-base
func (UnimplementedHandler) GetKnowledgeBaseListRoute(ctx context.Context, params GetKnowledgeBaseListRouteParams) (r GetKnowledgeBaseListRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLibraryVoices implements get_library_voices operation.
//
// Retrieves a list of shared voices.
//
// GET /v1/shared-voices
func (UnimplementedHandler) GetLibraryVoices(ctx context.Context, params GetLibraryVoicesParams) (r GetLibraryVoicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLiveCount implements get_live_count operation.
//
// Get the live count of the ongoing conversations.
//
// GET /v1/convai/analytics/live-count
func (UnimplementedHandler) GetLiveCount(ctx context.Context, params GetLiveCountParams) (r GetLiveCountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLivekitToken implements get_livekit_token operation.
//
// Get a WebRTC session token for real-time communication.
//
// GET /v1/convai/conversation/token
func (UnimplementedHandler) GetLivekitToken(ctx context.Context, params GetLivekitTokenParams) (r GetLivekitTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMcpToolConfigOverrideRoute implements get_mcp_tool_config_override_route operation.
//
// Retrieve configuration overrides for a specific MCP tool.
//
// GET /v1/convai/mcp-servers/{mcp_server_id}/tool-configs/{tool_name}
func (UnimplementedHandler) GetMcpToolConfigOverrideRoute(ctx context.Context, params GetMcpToolConfigOverrideRouteParams) (r GetMcpToolConfigOverrideRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetModels implements get_models operation.
//
// Gets a list of available models.
//
// GET /v1/models
func (UnimplementedHandler) GetModels(ctx context.Context, params GetModelsParams) (r GetModelsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrCreateRagIndexes implements get_or_create_rag_indexes operation.
//
// Retrieves and/or creates RAG indexes for multiple knowledge base documents in a single request.
//
// POST /v1/convai/knowledge-base/rag-index
func (UnimplementedHandler) GetOrCreateRagIndexes(ctx context.Context, req *BodyComputeRAGIndexesInBatchV1ConvaiKnowledgeBaseRagIndexPost, params GetOrCreateRagIndexesParams) (r GetOrCreateRagIndexesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPhoneNumberRoute implements get_phone_number_route operation.
//
// Retrieve Phone Number details by ID.
//
// GET /v1/convai/phone-numbers/{phone_number_id}
func (UnimplementedHandler) GetPhoneNumberRoute(ctx context.Context, params GetPhoneNumberRouteParams) (r GetPhoneNumberRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectSnapshotEndpoint implements get_project_snapshot_endpoint operation.
//
// Returns the project snapshot.
//
// GET /v1/studio/projects/{project_id}/snapshots/{project_snapshot_id}
func (UnimplementedHandler) GetProjectSnapshotEndpoint(ctx context.Context, params GetProjectSnapshotEndpointParams) (r GetProjectSnapshotEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectSnapshots implements get_project_snapshots operation.
//
// Retrieves a list of snapshots for a Studio project.
//
// GET /v1/studio/projects/{project_id}/snapshots
func (UnimplementedHandler) GetProjectSnapshots(ctx context.Context, params GetProjectSnapshotsParams) (r GetProjectSnapshotsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjects implements get_projects operation.
//
// Returns a list of your Studio projects with metadata.
//
// GET /v1/studio/projects
func (UnimplementedHandler) GetProjects(ctx context.Context, params GetProjectsParams) (r GetProjectsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPronunciationDictionariesMetadata implements get_pronunciation_dictionaries_metadata operation.
//
// Get a list of the pronunciation dictionaries you have access to and their metadata.
//
// GET /v1/pronunciation-dictionaries
func (UnimplementedHandler) GetPronunciationDictionariesMetadata(ctx context.Context, params GetPronunciationDictionariesMetadataParams) (r GetPronunciationDictionariesMetadataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPronunciationDictionaryMetadata implements get_pronunciation_dictionary_metadata operation.
//
// Get metadata for a pronunciation dictionary.
//
// GET /v1/pronunciation-dictionaries/{pronunciation_dictionary_id}
func (UnimplementedHandler) GetPronunciationDictionaryMetadata(ctx context.Context, params GetPronunciationDictionaryMetadataParams) (r GetPronunciationDictionaryMetadataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPronunciationDictionaryVersionPls implements get_pronunciation_dictionary_version_pls operation.
//
// Get a PLS file with a pronunciation dictionary version rules.
//
// GET /v1/pronunciation-dictionaries/{dictionary_id}/{version_id}/download
func (UnimplementedHandler) GetPronunciationDictionaryVersionPls(ctx context.Context, params GetPronunciationDictionaryVersionPlsParams) (r GetPronunciationDictionaryVersionPlsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPublicLlmExpectedCostCalculation implements get_public_llm_expected_cost_calculation operation.
//
// Returns a list of LLM models and the expected cost for using them based on the provided values.
//
// POST /v1/convai/llm-usage/calculate
func (UnimplementedHandler) GetPublicLlmExpectedCostCalculation(ctx context.Context, req *LLMUsageCalculatorPublicRequestModel) (r GetPublicLlmExpectedCostCalculationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPvcSampleAudio implements get_pvc_sample_audio operation.
//
// Retrieve the first 30 seconds of voice sample audio with or without noise removal.
//
// GET /v1/voices/pvc/{voice_id}/samples/{sample_id}/audio
func (UnimplementedHandler) GetPvcSampleAudio(ctx context.Context, params GetPvcSampleAudioParams) (r GetPvcSampleAudioRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPvcSampleSpeakers implements get_pvc_sample_speakers operation.
//
// Retrieve the status of the speaker separation process and the list of detected speakers if
// complete.
//
// GET /v1/voices/pvc/{voice_id}/samples/{sample_id}/speakers
func (UnimplementedHandler) GetPvcSampleSpeakers(ctx context.Context, params GetPvcSampleSpeakersParams) (r GetPvcSampleSpeakersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPvcSampleVisualWaveform implements get_pvc_sample_visual_waveform operation.
//
// Retrieve the visual waveform of a voice sample.
//
// GET /v1/voices/pvc/{voice_id}/samples/{sample_id}/waveform
func (UnimplementedHandler) GetPvcSampleVisualWaveform(ctx context.Context, params GetPvcSampleVisualWaveformParams) (r GetPvcSampleVisualWaveformRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPvcVoiceCaptcha implements get_pvc_voice_captcha operation.
//
// Get captcha for PVC voice verification.
//
// GET /v1/voices/pvc/{voice_id}/captcha
func (UnimplementedHandler) GetPvcVoiceCaptcha(ctx context.Context, params GetPvcVoiceCaptchaParams) (r GetPvcVoiceCaptchaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRagIndexOverview implements get_rag_index_overview operation.
//
// Provides total size and other information of RAG indexes used by knowledgebase documents.
//
// GET /v1/convai/knowledge-base/rag-index
func (UnimplementedHandler) GetRagIndexOverview(ctx context.Context, params GetRagIndexOverviewParams) (r GetRagIndexOverviewRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRagIndexes implements get_rag_indexes operation.
//
// Provides information about all RAG indexes of the specified knowledgebase document.
//
// GET /v1/convai/knowledge-base/{documentation_id}/rag-index
func (UnimplementedHandler) GetRagIndexes(ctx context.Context, params GetRagIndexesParams) (r GetRagIndexesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetResourceMetadata implements get_resource_metadata operation.
//
// Gets the metadata of a resource by ID.
//
// GET /v1/workspace/resources/{resource_id}
func (UnimplementedHandler) GetResourceMetadata(ctx context.Context, params GetResourceMetadataParams) (r GetResourceMetadataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSecretsRoute implements get_secrets_route operation.
//
// Get all workspace secrets for the user.
//
// GET /v1/convai/secrets
func (UnimplementedHandler) GetSecretsRoute(ctx context.Context, params GetSecretsRouteParams) (r GetSecretsRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServiceAccountAPIKeysRoute implements get_service_account_api_keys_route operation.
//
// Get all API keys for a service account.
//
// GET /v1/service-accounts/{service_account_user_id}/api-keys
func (UnimplementedHandler) GetServiceAccountAPIKeysRoute(ctx context.Context, params GetServiceAccountAPIKeysRouteParams) (r GetServiceAccountAPIKeysRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSettingsRoute implements get_settings_route operation.
//
// Retrieve Convai settings for the workspace.
//
// GET /v1/convai/settings
func (UnimplementedHandler) GetSettingsRoute(ctx context.Context, params GetSettingsRouteParams) (r GetSettingsRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSignedURLDeprecated implements get_signed_url_deprecated operation.
//
// Get a signed url to start a conversation with an agent with an agent that requires authorization.
//
// Deprecated: schema marks this operation as deprecated.
//
// GET /v1/convai/conversation/get_signed_url
func (UnimplementedHandler) GetSignedURLDeprecated(ctx context.Context, params GetSignedURLDeprecatedParams) (r GetSignedURLDeprecatedRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSimilarLibraryVoices implements get_similar_library_voices operation.
//
// Returns a list of shared voices similar to the provided audio sample. If neither
// similarity_threshold nor top_k is provided, we will apply default values.
//
// POST /v1/similar-voices
func (UnimplementedHandler) GetSimilarLibraryVoices(ctx context.Context, req OptBodyGetSimilarLibraryVoicesV1SimilarVoicesPostMultipart, params GetSimilarLibraryVoicesParams) (r GetSimilarLibraryVoicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSimilarVoicesForSpeaker implements get_similar_voices_for_speaker operation.
//
// Fetch the top 10 similar voices to a speaker, including the voice IDs, names, descriptions, and,
// where possible, a sample audio recording.
//
// GET /v1/dubbing/resource/{dubbing_id}/speaker/{speaker_id}/similar-voices
func (UnimplementedHandler) GetSimilarVoicesForSpeaker(ctx context.Context, params GetSimilarVoicesForSpeakerParams) (r GetSimilarVoicesForSpeakerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSingleUseToken implements get_single_use_token operation.
//
// Generate a time limited single-use token with embedded authentication for frontend clients.
//
// POST /v1/single-use-token/{token_type}
func (UnimplementedHandler) GetSingleUseToken(ctx context.Context, params GetSingleUseTokenParams) (r GetSingleUseTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpeakerAudio implements get_speaker_audio operation.
//
// Retrieve the separated audio for a specific speaker.
//
// GET /v1/voices/pvc/{voice_id}/samples/{sample_id}/speakers/{speaker_id}/audio
func (UnimplementedHandler) GetSpeakerAudio(ctx context.Context, params GetSpeakerAudioParams) (r GetSpeakerAudioRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpeechHistory implements get_speech_history operation.
//
// Returns a list of your generated audio.
//
// GET /v1/history
func (UnimplementedHandler) GetSpeechHistory(ctx context.Context, params GetSpeechHistoryParams) (r GetSpeechHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpeechHistoryItemByID implements get_speech_history_item_by_id operation.
//
// Retrieves a history item.
//
// GET /v1/history/{history_item_id}
func (UnimplementedHandler) GetSpeechHistoryItemByID(ctx context.Context, params GetSpeechHistoryItemByIDParams) (r GetSpeechHistoryItemByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTestInvocationRoute implements get_test_invocation_route operation.
//
// Gets a test invocation by ID.
//
// GET /v1/convai/test-invocations/{test_invocation_id}
func (UnimplementedHandler) GetTestInvocationRoute(ctx context.Context, params GetTestInvocationRouteParams) (r GetTestInvocationRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetToolDependentAgentsRoute implements get_tool_dependent_agents_route operation.
//
// Get a list of agents depending on this tool.
//
// GET /v1/convai/tools/{tool_id}/dependent-agents
func (UnimplementedHandler) GetToolDependentAgentsRoute(ctx context.Context, params GetToolDependentAgentsRouteParams) (r GetToolDependentAgentsRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTranscriptByID implements get_transcript_by_id operation.
//
// Retrieve a previously generated transcript by its ID.
//
// GET /v1/speech-to-text/transcripts/{transcription_id}
func (UnimplementedHandler) GetTranscriptByID(ctx context.Context, params GetTranscriptByIDParams) (r GetTranscriptByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserInfo implements get_user_info operation.
//
// Gets information about the user.
//
// GET /v1/user
func (UnimplementedHandler) GetUserInfo(ctx context.Context, params GetUserInfoParams) (r GetUserInfoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserVoicesV2 implements get_user_voices_v2 operation.
//
// Gets a list of all available voices for a user with search, filtering and pagination.
//
// GET /v2/voices
func (UnimplementedHandler) GetUserVoicesV2(ctx context.Context, params GetUserVoicesV2Params) (r GetUserVoicesV2Res, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVoiceByID implements get_voice_by_id operation.
//
// Returns metadata about a specific voice.
//
// GET /v1/voices/{voice_id}
func (UnimplementedHandler) GetVoiceByID(ctx context.Context, params GetVoiceByIDParams) (r GetVoiceByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVoiceSettings implements get_voice_settings operation.
//
// Returns the settings for a specific voice. "similarity_boost" corresponds to"Clarity + Similarity
// Enhancement" in the web app and "stability" corresponds to "Stability" slider in the web app.
//
// GET /v1/voices/{voice_id}/settings
func (UnimplementedHandler) GetVoiceSettings(ctx context.Context, params GetVoiceSettingsParams) (r GetVoiceSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVoiceSettingsDefault implements get_voice_settings_default operation.
//
// Gets the default settings for voices. "similarity_boost" corresponds to"Clarity + Similarity
// Enhancement" in the web app and "stability" corresponds to "Stability" slider in the web app.
//
// GET /v1/voices/settings/default
func (UnimplementedHandler) GetVoiceSettingsDefault(ctx context.Context) (r *VoiceSettingsResponseModel, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVoices implements get_voices operation.
//
// Returns a list of all available voices for a user.
//
// GET /v1/voices
func (UnimplementedHandler) GetVoices(ctx context.Context, params GetVoicesParams) (r GetVoicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWhatsappAccount implements get_whatsapp_account operation.
//
// Get a WhatsApp account.
//
// GET /v1/convai/whatsapp-accounts/{phone_number_id}
func (UnimplementedHandler) GetWhatsappAccount(ctx context.Context, params GetWhatsappAccountParams) (r GetWhatsappAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceBatchCalls implements get_workspace_batch_calls operation.
//
// Get all batch calls for the current workspace.
//
// GET /v1/convai/batch-calling/workspace
func (UnimplementedHandler) GetWorkspaceBatchCalls(ctx context.Context, params GetWorkspaceBatchCallsParams) (r GetWorkspaceBatchCallsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceServiceAccounts implements get_workspace_service_accounts operation.
//
// List all service accounts in the workspace.
//
// GET /v1/service-accounts
func (UnimplementedHandler) GetWorkspaceServiceAccounts(ctx context.Context, params GetWorkspaceServiceAccountsParams) (r GetWorkspaceServiceAccountsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceWebhooksRoute implements get_workspace_webhooks_route operation.
//
// List all webhooks for a workspace.
//
// GET /v1/workspace/webhooks
func (UnimplementedHandler) GetWorkspaceWebhooksRoute(ctx context.Context, params GetWorkspaceWebhooksRouteParams) (r GetWorkspaceWebhooksRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HandleSipTrunkOutboundCall implements handle_sip_trunk_outbound_call operation.
//
// Handle an outbound call via SIP trunk.
//
// POST /v1/convai/sip-trunk/outbound-call
func (UnimplementedHandler) HandleSipTrunkOutboundCall(ctx context.Context, req *BodyHandleAnOutboundCallViaSIPTrunkV1ConvaiSipTrunkOutboundCallPost, params HandleSipTrunkOutboundCallParams) (r HandleSipTrunkOutboundCallRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HandleTwilioOutboundCall implements handle_twilio_outbound_call operation.
//
// Handle an outbound call via Twilio.
//
// POST /v1/convai/twilio/outbound-call
func (UnimplementedHandler) HandleTwilioOutboundCall(ctx context.Context, req *BodyHandleAnOutboundCallViaTwilioV1ConvaiTwilioOutboundCallPost, params HandleTwilioOutboundCallParams) (r HandleTwilioOutboundCallRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportWhatsappAccount implements import_whatsapp_account operation.
//
// Import a WhatsApp account.
//
// POST /v1/convai/whatsapp-accounts
func (UnimplementedHandler) ImportWhatsappAccount(ctx context.Context, req *ImportWhatsAppAccountRequest, params ImportWhatsappAccountParams) (r ImportWhatsappAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// InviteUser implements invite_user operation.
//
// Sends an email invitation to join your workspace to the provided email. If the user doesn't have
// an account they will be prompted to create one. If the user accepts this invite they will be added
// as a user to your workspace and your subscription using one of your seats. This endpoint may only
// be called by workspace administrators. If the user is already in the workspace a 400 error will be
// returned.
//
// POST /v1/workspace/invites/add
func (UnimplementedHandler) InviteUser(ctx context.Context, req *BodyInviteUserV1WorkspaceInvitesAddPost, params InviteUserParams) (r InviteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// InviteUsersBulk implements invite_users_bulk operation.
//
// Sends email invitations to join your workspace to the provided emails. Requires all email
// addresses to be part of a verified domain. If the users don't have an account they will be
// prompted to create one. If the users accept these invites they will be added as users to your
// workspace and your subscription using one of your seats. This endpoint may only be called by
// workspace administrators.
//
// POST /v1/workspace/invites/add-bulk
func (UnimplementedHandler) InviteUsersBulk(ctx context.Context, req *BodyInviteMultipleUsersV1WorkspaceInvitesAddBulkPost, params InviteUsersBulkParams) (r InviteUsersBulkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListChatResponseTestsRoute implements list_chat_response_tests_route operation.
//
// Lists all agent response tests with pagination support and optional search filtering.
//
// GET /v1/convai/agent-testing
func (UnimplementedHandler) ListChatResponseTestsRoute(ctx context.Context, params ListChatResponseTestsRouteParams) (r ListChatResponseTestsRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDubs implements list_dubs operation.
//
// List the dubs you have access to.
//
// GET /v1/dubbing
func (UnimplementedHandler) ListDubs(ctx context.Context, params ListDubsParams) (r ListDubsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMcpServerToolsRoute implements list_mcp_server_tools_route operation.
//
// Retrieve all tools available for a specific MCP server configuration.
//
// GET /v1/convai/mcp-servers/{mcp_server_id}/tools
func (UnimplementedHandler) ListMcpServerToolsRoute(ctx context.Context, params ListMcpServerToolsRouteParams) (r ListMcpServerToolsRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPhoneNumbersRoute implements list_phone_numbers_route operation.
//
// Retrieve all Phone Numbers.
//
// GET /v1/convai/phone-numbers
func (UnimplementedHandler) ListPhoneNumbersRoute(ctx context.Context, params ListPhoneNumbersRouteParams) (r ListPhoneNumbersRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTestInvocationsRoute implements list_test_invocations_route operation.
//
// Lists all test invocations with pagination support and optional search filtering.
//
// GET /v1/convai/test-invocations
func (UnimplementedHandler) ListTestInvocationsRoute(ctx context.Context, params ListTestInvocationsRouteParams) (r ListTestInvocationsRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWhatsappAccounts implements list_whatsapp_accounts operation.
//
// List all WhatsApp accounts.
//
// GET /v1/convai/whatsapp-accounts
func (UnimplementedHandler) ListWhatsappAccounts(ctx context.Context, params ListWhatsappAccountsParams) (r ListWhatsappAccountsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MigrateSegments implements migrate_segments operation.
//
// Change the attribution of one or more segments to a different speaker.
//
// POST /v1/dubbing/resource/{dubbing_id}/migrate-segments
func (UnimplementedHandler) MigrateSegments(ctx context.Context, req *BodyMoveSegmentsBetweenSpeakersV1DubbingResourceDubbingIDMigrateSegmentsPost, params MigrateSegmentsParams) (r MigrateSegmentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchPronunciationDictionary implements patch_pronunciation_dictionary operation.
//
// Partially update the pronunciation dictionary without changing the version.
//
// PATCH /v1/pronunciation-dictionaries/{pronunciation_dictionary_id}
func (UnimplementedHandler) PatchPronunciationDictionary(ctx context.Context, req OptBodyUpdatePronunciationDictionaryV1PronunciationDictionariesPronunciationDictionaryIDPatch, params PatchPronunciationDictionaryParams) (r PatchPronunciationDictionaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostAgentAvatarRoute implements post_agent_avatar_route operation.
//
// Sets the avatar for an agent displayed in the widget.
//
// POST /v1/convai/agents/{agent_id}/avatar
func (UnimplementedHandler) PostAgentAvatarRoute(ctx context.Context, req *BodyPostAgentAvatarV1ConvaiAgentsAgentIDAvatarPostMultipart, params PostAgentAvatarRouteParams) (r PostAgentAvatarRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostConversationFeedbackRoute implements post_conversation_feedback_route operation.
//
// Send the feedback for the given conversation.
//
// POST /v1/convai/conversations/{conversation_id}/feedback
func (UnimplementedHandler) PostConversationFeedbackRoute(ctx context.Context, req *ConversationFeedbackRequestModel, params PostConversationFeedbackRouteParams) (r PostConversationFeedbackRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RagIndexStatus implements rag_index_status operation.
//
// In case the document is not RAG indexed, it triggers rag indexing task, otherwise it just returns
// the current status.
//
// POST /v1/convai/knowledge-base/{documentation_id}/rag-index
func (UnimplementedHandler) RagIndexStatus(ctx context.Context, req *RAGIndexRequestModel, params RagIndexStatusParams) (r RagIndexStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RedirectToMintlify implements redirect_to_mintlify operation.
//
// Redirect To Mintlify.
//
// GET /docs
func (UnimplementedHandler) RedirectToMintlify(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterTwilioCall implements register_twilio_call operation.
//
// Register a Twilio call and return TwiML to connect the call.
//
// POST /v1/convai/twilio/register-call
func (UnimplementedHandler) RegisterTwilioCall(ctx context.Context, req *BodyRegisterATwilioCallAndReturnTwiMLV1ConvaiTwilioRegisterCallPost, params RegisterTwilioCallParams) (r RegisterTwilioCallRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveMember implements remove_member operation.
//
// Removes a member from the specified group. This endpoint may only be called by workspace
// administrators.
//
// POST /v1/workspace/groups/{group_id}/members/remove
func (UnimplementedHandler) RemoveMember(ctx context.Context, req *BodyDeleteMemberFromUserGroupV1WorkspaceGroupsGroupIDMembersRemovePost, params RemoveMemberParams) (r RemoveMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveRules implements remove_rules operation.
//
// Remove rules from the pronunciation dictionary.
//
// POST /v1/pronunciation-dictionaries/{pronunciation_dictionary_id}/remove-rules
func (UnimplementedHandler) RemoveRules(ctx context.Context, req *BodyRemoveRulesFromThePronunciationDictionaryV1PronunciationDictionariesPronunciationDictionaryIDRemoveRulesPost, params RemoveRulesParams) (r RemoveRulesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RequestPvcManualVerification implements request_pvc_manual_verification operation.
//
// Request manual verification for a PVC voice.
//
// POST /v1/voices/pvc/{voice_id}/verification
func (UnimplementedHandler) RequestPvcManualVerification(ctx context.Context, req *BodyRequestManualVerificationV1VoicesPvcVoiceIDVerificationPostMultipart, params RequestPvcManualVerificationParams) (r RequestPvcManualVerificationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RetryBatchCall implements retry_batch_call operation.
//
// Retry a batch call, calling failed and no-response recipients again.
//
// POST /v1/convai/batch-calling/{batch_id}/retry
func (UnimplementedHandler) RetryBatchCall(ctx context.Context, params RetryBatchCallParams) (r RetryBatchCallRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RunPvcVoiceTraining implements run_pvc_voice_training operation.
//
// Start PVC training process for a voice.
//
// POST /v1/voices/pvc/{voice_id}/train
func (UnimplementedHandler) RunPvcVoiceTraining(ctx context.Context, req OptBodyRunPVCTrainingV1VoicesPvcVoiceIDTrainPost, params RunPvcVoiceTrainingParams) (r RunPvcVoiceTrainingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchGroups implements search_groups operation.
//
// Searches for user groups in the workspace. Multiple or no groups may be returned.
//
// GET /v1/workspace/groups/search
func (UnimplementedHandler) SearchGroups(ctx context.Context, params SearchGroupsParams) (r SearchGroupsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SeparateSongStems implements separate_song_stems operation.
//
// Separate an audio file into individual stems. This endpoint might have high latency, depending on
// the length of the audio file.
//
// POST /v1/music/stem-separation
func (UnimplementedHandler) SeparateSongStems(ctx context.Context, req *BodyStemSeparationV1MusicStemSeparationPostMultipart, params SeparateSongStemsParams) (r SeparateSongStemsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ShareResourceEndpoint implements share_resource_endpoint operation.
//
// Grants a role on a workspace resource to a user or a group. It overrides any existing role this
// user/service account/group/workspace api key has on the resource. To target a user or service
// account, pass only the user email. The user must be in your workspace. To target a group, pass
// only the group id. To target a workspace api key, pass the api key id. The resource will be shared
// with the service account associated with the api key. You must have admin access to the resource
// to share it.
//
// POST /v1/workspace/resources/{resource_id}/share
func (UnimplementedHandler) ShareResourceEndpoint(ctx context.Context, req *BodyShareWorkspaceResourceV1WorkspaceResourcesResourceIDSharePost, params ShareResourceEndpointParams) (r ShareResourceEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SoundGeneration implements sound_generation operation.
//
// Turn text into sound effects for your videos, voice-overs or video games using the most advanced
// sound effects models in the world.
//
// POST /v1/sound-generation
func (UnimplementedHandler) SoundGeneration(ctx context.Context, req *BodySoundGenerationV1SoundGenerationPost, params SoundGenerationParams) (r SoundGenerationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SpeechToSpeechFull implements speech_to_speech_full operation.
//
// Transform audio from one voice to another. Maintain full control over emotion, timing and delivery.
//
// POST /v1/speech-to-speech/{voice_id}
func (UnimplementedHandler) SpeechToSpeechFull(ctx context.Context, req *BodySpeechToSpeechV1SpeechToSpeechVoiceIDPostMultipart, params SpeechToSpeechFullParams) (r SpeechToSpeechFullRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SpeechToSpeechStream implements speech_to_speech_stream operation.
//
// Stream audio from one voice to another. Maintain full control over emotion, timing and delivery.
//
// POST /v1/speech-to-speech/{voice_id}/stream
func (UnimplementedHandler) SpeechToSpeechStream(ctx context.Context, req *BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIDStreamPostMultipart, params SpeechToSpeechStreamParams) (r SpeechToSpeechStreamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SpeechToText implements speech_to_text operation.
//
// Transcribe an audio or video file. If webhook is set to true, the request will be processed
// asynchronously and results sent to configured webhooks. When use_multi_channel is true and the
// provided audio has multiple channels, a 'transcripts' object with separate transcripts for each
// channel is returned. Otherwise, returns a single transcript. The optional webhook_metadata
// parameter allows you to attach custom data that will be included in webhook responses for request
// correlation and tracking.
//
// POST /v1/speech-to-text
func (UnimplementedHandler) SpeechToText(ctx context.Context, req *BodySpeechToTextV1SpeechToTextPostMultipart, params SpeechToTextParams) (r SpeechToTextRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartSpeakerSeparation implements start_speaker_separation operation.
//
// Start speaker separation process for a sample.
//
// POST /v1/voices/pvc/{voice_id}/samples/{sample_id}/separate-speakers
func (UnimplementedHandler) StartSpeakerSeparation(ctx context.Context, params StartSpeakerSeparationParams) (r StartSpeakerSeparationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StreamChapterSnapshotAudio implements stream_chapter_snapshot_audio operation.
//
// Stream the audio from a chapter snapshot. Use `GET
// /v1/studio/projects/{project_id}/chapters/{chapter_id}/snapshots` to return the snapshots of a
// chapter.
//
// POST /v1/studio/projects/{project_id}/chapters/{chapter_id}/snapshots/{chapter_snapshot_id}/stream
func (UnimplementedHandler) StreamChapterSnapshotAudio(ctx context.Context, req OptBodyStreamChapterAudioV1StudioProjectsProjectIDChaptersChapterIDSnapshotsChapterSnapshotIDStreamPost, params StreamChapterSnapshotAudioParams) (r StreamChapterSnapshotAudioRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StreamCompose implements stream_compose operation.
//
// Stream a composed song from a prompt or a composition plan.
//
// POST /v1/music/stream
func (UnimplementedHandler) StreamCompose(ctx context.Context, req OptBodyStreamComposedMusicV1MusicStreamPost, params StreamComposeParams) (r StreamComposeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StreamProjectSnapshotArchiveEndpoint implements stream_project_snapshot_archive_endpoint operation.
//
// Returns a compressed archive of the Studio project's audio.
//
// POST /v1/studio/projects/{project_id}/snapshots/{project_snapshot_id}/archive
func (UnimplementedHandler) StreamProjectSnapshotArchiveEndpoint(ctx context.Context, params StreamProjectSnapshotArchiveEndpointParams) (r StreamProjectSnapshotArchiveEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StreamProjectSnapshotAudioEndpoint implements stream_project_snapshot_audio_endpoint operation.
//
// Stream the audio from a Studio project snapshot.
//
// POST /v1/studio/projects/{project_id}/snapshots/{project_snapshot_id}/stream
func (UnimplementedHandler) StreamProjectSnapshotAudioEndpoint(ctx context.Context, req OptBodyStreamStudioProjectAudioV1StudioProjectsProjectIDSnapshotsProjectSnapshotIDStreamPost, params StreamProjectSnapshotAudioEndpointParams) (r StreamProjectSnapshotAudioEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToDialogue implements text_to_dialogue operation.
//
// Converts a list of text and voice ID pairs into speech (dialogue) and returns audio.
//
// POST /v1/text-to-dialogue
func (UnimplementedHandler) TextToDialogue(ctx context.Context, req *BodyTextToDialogueMultiVoiceV1TextToDialoguePost, params TextToDialogueParams) (r TextToDialogueRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToDialogueFullWithTimestamps implements text_to_dialogue_full_with_timestamps operation.
//
// Generate dialogue from text with precise character-level timing information for audio-text
// synchronization.
//
// POST /v1/text-to-dialogue/with-timestamps
func (UnimplementedHandler) TextToDialogueFullWithTimestamps(ctx context.Context, req *BodyTextToDialogueFullWithTimestamps, params TextToDialogueFullWithTimestampsParams) (r TextToDialogueFullWithTimestampsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToDialogueStream implements text_to_dialogue_stream operation.
//
// Converts a list of text and voice ID pairs into speech (dialogue) and returns an audio stream.
//
// POST /v1/text-to-dialogue/stream
func (UnimplementedHandler) TextToDialogueStream(ctx context.Context, req *BodyTextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPost, params TextToDialogueStreamParams) (r TextToDialogueStreamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToDialogueStreamWithTimestamps implements text_to_dialogue_stream_with_timestamps operation.
//
// Converts a list of text and voice ID pairs into speech (dialogue) and returns a stream of JSON
// blobs containing audio as a base64 encoded string and timestamps.
//
// POST /v1/text-to-dialogue/stream/with-timestamps
func (UnimplementedHandler) TextToDialogueStreamWithTimestamps(ctx context.Context, req *BodyTextToDialogueStreamWithTimestamps, params TextToDialogueStreamWithTimestampsParams) (r TextToDialogueStreamWithTimestampsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToSpeechFull implements text_to_speech_full operation.
//
// Converts text into speech using a voice of your choice and returns audio.
//
// POST /v1/text-to-speech/{voice_id}
func (UnimplementedHandler) TextToSpeechFull(ctx context.Context, req *BodyTextToSpeechFull, params TextToSpeechFullParams) (r TextToSpeechFullRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToSpeechFullWithTimestamps implements text_to_speech_full_with_timestamps operation.
//
// Generate speech from text with precise character-level timing information for audio-text
// synchronization.
//
// POST /v1/text-to-speech/{voice_id}/with-timestamps
func (UnimplementedHandler) TextToSpeechFullWithTimestamps(ctx context.Context, req *BodyTextToSpeechFullWithTimestamps, params TextToSpeechFullWithTimestampsParams) (r TextToSpeechFullWithTimestampsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToSpeechStream implements text_to_speech_stream operation.
//
// Converts text into speech using a voice of your choice and returns audio as an audio stream.
//
// POST /v1/text-to-speech/{voice_id}/stream
func (UnimplementedHandler) TextToSpeechStream(ctx context.Context, req *BodyTextToSpeechStream, params TextToSpeechStreamParams) (r TextToSpeechStreamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToSpeechStreamWithTimestamps implements text_to_speech_stream_with_timestamps operation.
//
// Converts text into speech using a voice of your choice and returns a stream of JSONs containing
// audio as a base64 encoded string together with information on when which character was spoken.
//
// POST /v1/text-to-speech/{voice_id}/stream/with-timestamps
func (UnimplementedHandler) TextToSpeechStreamWithTimestamps(ctx context.Context, req *BodyTextToSpeechStreamWithTimestamps, params TextToSpeechStreamWithTimestampsParams) (r TextToSpeechStreamWithTimestampsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToVoice implements text_to_voice operation.
//
// Generate a custom voice based on voice description. This method returns a list of voice previews.
// Each preview has a generated_voice_id and a sample of the voice as base64 encoded mp3 audio. If
// you like the a voice previewand want to create the voice call
// /v1/text-to-voice/create-voice-from-preview with the generated_voice_id to create the voice.
//
// POST /v1/text-to-voice/create-previews
func (UnimplementedHandler) TextToVoice(ctx context.Context, req *VoicePreviewsRequestModel, params TextToVoiceParams) (r TextToVoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToVoiceDesign implements text_to_voice_design operation.
//
// Design a voice via a prompt. This method returns a list of voice previews. Each preview has a
// generated_voice_id and a sample of the voice as base64 encoded mp3 audio. To create a voice use
// the generated_voice_id of the preferred preview with the /v1/text-to-voice endpoint.
//
// POST /v1/text-to-voice/design
func (UnimplementedHandler) TextToVoiceDesign(ctx context.Context, req *VoiceDesignRequestModel, params TextToVoiceDesignParams) (r TextToVoiceDesignRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToVoicePreviewStream implements text_to_voice_preview_stream operation.
//
// Stream a voice preview that was created via the /v1/text-to-voice/design endpoint.
//
// GET /v1/text-to-voice/{generated_voice_id}/stream
func (UnimplementedHandler) TextToVoicePreviewStream(ctx context.Context, params TextToVoicePreviewStreamParams) (r TextToVoicePreviewStreamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToVoiceRemix implements text_to_voice_remix operation.
//
// Remix an existing voice via a prompt. This method returns a list of voice previews. Each preview
// has a generated_voice_id and a sample of the voice as base64 encoded mp3 audio. To create a voice
// use the generated_voice_id of the preferred preview with the /v1/text-to-voice endpoint.
//
// POST /v1/text-to-voice/{voice_id}/remix
func (UnimplementedHandler) TextToVoiceRemix(ctx context.Context, req *VoiceRemixRequestModel, params TextToVoiceRemixParams) (r TextToVoiceRemixRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Transcribe implements transcribe operation.
//
// Regenerate the transcriptions for the specified segments. Does not automatically regenerate
// translations or dubs.
//
// POST /v1/dubbing/resource/{dubbing_id}/transcribe
func (UnimplementedHandler) Transcribe(ctx context.Context, req *BodyTranscribesSegmentsV1DubbingResourceDubbingIDTranscribePost, params TranscribeParams) (r TranscribeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Translate implements translate operation.
//
// Regenerate the translations for either the entire resource or the specified segments/languages.
// Will automatically transcribe missing transcriptions. Will not automatically regenerate the dubs.
//
// POST /v1/dubbing/resource/{dubbing_id}/translate
func (UnimplementedHandler) Translate(ctx context.Context, req *BodyTranslatesAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIDTranslatePost, params TranslateParams) (r TranslateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UnshareResourceEndpoint implements unshare_resource_endpoint operation.
//
// Removes any existing role on a workspace resource from a user, service account, group or workspace
// api key. To target a user or service account, pass only the user email. The user must be in your
// workspace. To target a group, pass only the group id. To target a workspace api key, pass the api
// key id. The resource will be unshared from the service account associated with the api key. You
// must have admin access to the resource to unshare it. You cannot remove permissions from the user
// who created the resource.
//
// POST /v1/workspace/resources/{resource_id}/unshare
func (UnimplementedHandler) UnshareResourceEndpoint(ctx context.Context, req *BodyUnshareWorkspaceResourceV1WorkspaceResourcesResourceIDUnsharePost, params UnshareResourceEndpointParams) (r UnshareResourceEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAgentResponseTestRoute implements update_agent_response_test_route operation.
//
// Updates an agent response test by ID.
//
// PUT /v1/convai/agent-testing/{test_id}
func (UnimplementedHandler) UpdateAgentResponseTestRoute(ctx context.Context, req *UpdateUnitTestRequest, params UpdateAgentResponseTestRouteParams) (r UpdateAgentResponseTestRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDashboardSettingsRoute implements update_dashboard_settings_route operation.
//
// Update Convai dashboard settings for the workspace.
//
// PATCH /v1/convai/settings/dashboard
func (UnimplementedHandler) UpdateDashboardSettingsRoute(ctx context.Context, req *PatchConvAIDashboardSettingsRequest, params UpdateDashboardSettingsRouteParams) (r UpdateDashboardSettingsRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDocumentRoute implements update_document_route operation.
//
// Update the name of a document.
//
// PATCH /v1/convai/knowledge-base/{documentation_id}
func (UnimplementedHandler) UpdateDocumentRoute(ctx context.Context, req *BodyUpdateDocumentV1ConvaiKnowledgeBaseDocumentationIDPatch, params UpdateDocumentRouteParams) (r UpdateDocumentRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePhoneNumberRoute implements update_phone_number_route operation.
//
// Update assigned agent of a phone number.
//
// PATCH /v1/convai/phone-numbers/{phone_number_id}
func (UnimplementedHandler) UpdatePhoneNumberRoute(ctx context.Context, req *UpdatePhoneNumberRequest, params UpdatePhoneNumberRouteParams) (r UpdatePhoneNumberRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePronunciationDictionaries implements update_pronunciation_dictionaries operation.
//
// Create a set of pronunciation dictionaries acting on a project. This will automatically mark text
// within this project as requiring reconverting where the new dictionary would apply or the old one
// no longer does.
//
// POST /v1/studio/projects/{project_id}/pronunciation-dictionaries
func (UnimplementedHandler) UpdatePronunciationDictionaries(ctx context.Context, req *BodyCreatePronunciationDictionariesV1StudioProjectsProjectIDPronunciationDictionariesPost, params UpdatePronunciationDictionariesParams) (r UpdatePronunciationDictionariesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSecretRoute implements update_secret_route operation.
//
// Update an existing secret for the workspace.
//
// PATCH /v1/convai/secrets/{secret_id}
func (UnimplementedHandler) UpdateSecretRoute(ctx context.Context, req *PatchWorkspaceSecretRequest, params UpdateSecretRouteParams) (r UpdateSecretRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSegmentLanguage implements update_segment_language operation.
//
// Modifies a single segment with new text and/or start/end times. Will update the values for only a
// specific language of a segment. Does not automatically regenerate the dub.
//
// PATCH /v1/dubbing/resource/{dubbing_id}/segment/{segment_id}/{language}
func (UnimplementedHandler) UpdateSegmentLanguage(ctx context.Context, req *SegmentUpdatePayload, params UpdateSegmentLanguageParams) (r UpdateSegmentLanguageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSettingsRoute implements update_settings_route operation.
//
// Update Convai settings for the workspace.
//
// PATCH /v1/convai/settings
func (UnimplementedHandler) UpdateSettingsRoute(ctx context.Context, req *PatchConvAISettingsRequest, params UpdateSettingsRouteParams) (r UpdateSettingsRouteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSpeaker implements update_speaker operation.
//
// Amend the metadata associated with a speaker, such as their voice. Both voice cloning and using
// voices from the ElevenLabs library are supported.
//
// PATCH /v1/dubbing/resource/{dubbing_id}/speaker/{speaker_id}
func (UnimplementedHandler) UpdateSpeaker(ctx context.Context, req OptBodyUpdateMetadataForASpeakerV1DubbingResourceDubbingIDSpeakerSpeakerIDPatch, params UpdateSpeakerParams) (r UpdateSpeakerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWhatsappAccount implements update_whatsapp_account operation.
//
// Update a WhatsApp account.
//
// PATCH /v1/convai/whatsapp-accounts/{phone_number_id}
func (UnimplementedHandler) UpdateWhatsappAccount(ctx context.Context, req *UpdateWhatsAppAccountRequest, params UpdateWhatsappAccountParams) (r UpdateWhatsappAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWorkspaceMember implements update_workspace_member operation.
//
// Updates attributes of a workspace member. Apart from the email identifier, all parameters will
// remain unchanged unless specified. This endpoint may only be called by workspace administrators.
//
// POST /v1/workspace/members
func (UnimplementedHandler) UpdateWorkspaceMember(ctx context.Context, req *BodyUpdateMemberV1WorkspaceMembersPost, params UpdateWorkspaceMemberParams) (r UpdateWorkspaceMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsageCharacters implements usage_characters operation.
//
// Returns the usage metrics for the current user or the entire workspace they are part of. The
// response provides a time axis based on the specified aggregation interval (default: day), with
// usage values for each interval along that axis. Usage is broken down by the selected breakdown
// type. For example, breakdown type "voice" will return the usage of each voice for each interval
// along the time axis.
//
// GET /v1/usage/character-stats
func (UnimplementedHandler) UsageCharacters(ctx context.Context, params UsageCharactersParams) (r UsageCharactersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// VerifyPvcVoiceCaptcha implements verify_pvc_voice_captcha operation.
//
// Submit captcha verification for PVC voice.
//
// POST /v1/voices/pvc/{voice_id}/captcha
func (UnimplementedHandler) VerifyPvcVoiceCaptcha(ctx context.Context, req *BodyVerifyPVCVoiceCaptchaV1VoicesPvcVoiceIDCaptchaPostMultipart, params VerifyPvcVoiceCaptchaParams) (r VerifyPvcVoiceCaptchaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WhatsappOutboundCall implements whatsapp_outbound_call operation.
//
// Make an outbound call via WhatsApp.
//
// POST /v1/convai/whatsapp/outbound-call
func (UnimplementedHandler) WhatsappOutboundCall(ctx context.Context, req *BodyMakeAnOutboundCallViaWhatsAppV1ConvaiWhatsappOutboundCallPost, params WhatsappOutboundCallParams) (r WhatsappOutboundCallRes, _ error) {
	return r, ht.ErrNotImplemented
}
