// Code generated by ogen, DO NOT EDIT.
package api

type AddDocumentationToKnowledgeBaseRes interface {
	addDocumentationToKnowledgeBaseRes()
}

type AddFromFileRes interface {
	addFromFileRes()
}

type AddLanguageRes interface {
	addLanguageRes()
}

type AddMemberRes interface {
	addMemberRes()
}

type AddProjectRes interface {
	addProjectRes()
}

type AddPvcVoiceSamplesRes interface {
	addPvcVoiceSamplesRes()
}

type AddSharingVoiceRes interface {
	addSharingVoiceRes()
}

type AddVoiceRes interface {
	addVoiceRes()
}

type AudioIsolationRes interface {
	audioIsolationRes()
}

type AudioIsolationStreamRes interface {
	audioIsolationStreamRes()
}

type AudioNativeProjectUpdateContentEndpointRes interface {
	audioNativeProjectUpdateContentEndpointRes()
}

type CancelBatchCallRes interface {
	cancelBatchCallRes()
}

type ComposeDetailedRes interface {
	composeDetailedRes()
}

type ComposePlanRes interface {
	composePlanRes()
}

type ConvertChapterEndpointRes interface {
	convertChapterEndpointRes()
}

type ConvertProjectEndpointRes interface {
	convertProjectEndpointRes()
}

type CreateAgentResponseTestRouteRes interface {
	createAgentResponseTestRouteRes()
}

type CreateAudioNativeProjectRes interface {
	createAudioNativeProjectRes()
}

type CreateBatchCallRes interface {
	createBatchCallRes()
}

type CreateClipRes interface {
	createClipRes()
}

type CreateDubbingRes interface {
	createDubbingRes()
}

type CreateFileDocumentRouteRes interface {
	createFileDocumentRouteRes()
}

type CreatePvcVoiceRes interface {
	createPvcVoiceRes()
}

type CreateSecretRouteRes interface {
	createSecretRouteRes()
}

type CreateServiceAccountAPIKeyRes interface {
	createServiceAccountAPIKeyRes()
}

type CreateSpeakerRes interface {
	createSpeakerRes()
}

type CreateTextDocumentRouteRes interface {
	createTextDocumentRouteRes()
}

type CreateURLDocumentRouteRes interface {
	createURLDocumentRouteRes()
}

type CreateVoiceOldRes interface {
	createVoiceOldRes()
}

type CreateVoiceRes interface {
	createVoiceRes()
}

type CreateWorkspaceWebhookRouteRes interface {
	createWorkspaceWebhookRouteRes()
}

type DeleteAgentRouteRes interface {
	deleteAgentRouteRes()
}

type DeleteChapterEndpointRes interface {
	deleteChapterEndpointRes()
}

type DeleteChatResponseTestRouteRes interface {
	deleteChatResponseTestRouteRes()
}

type DeleteConversationRouteRes interface {
	deleteConversationRouteRes()
}

type DeleteDubbingRes interface {
	deleteDubbingRes()
}

type DeleteInviteRes interface {
	deleteInviteRes()
}

type DeleteKnowledgeBaseDocumentRes interface {
	deleteKnowledgeBaseDocumentRes()
}

type DeleteMcpServerRouteRes interface {
	deleteMcpServerRouteRes()
}

type DeletePhoneNumberRouteRes interface {
	deletePhoneNumberRouteRes()
}

type DeleteProjectRes interface {
	deleteProjectRes()
}

type DeletePvcVoiceSampleRes interface {
	deletePvcVoiceSampleRes()
}

type DeleteRagIndexRes interface {
	deleteRagIndexRes()
}

type DeleteSampleRes interface {
	deleteSampleRes()
}

type DeleteSecretRouteRes interface {
	deleteSecretRouteRes()
}

type DeleteSegmentRes interface {
	deleteSegmentRes()
}

type DeleteServiceAccountAPIKeyRes interface {
	deleteServiceAccountAPIKeyRes()
}

type DeleteSpeechHistoryItemRes interface {
	deleteSpeechHistoryItemRes()
}

type DeleteToolRouteRes interface {
	deleteToolRouteRes()
}

type DeleteTranscriptByIDRes interface {
	deleteTranscriptByIDRes()
}

type DeleteVoiceRes interface {
	deleteVoiceRes()
}

type DeleteWhatsappAccountRes interface {
	deleteWhatsappAccountRes()
}

type DeleteWorkspaceWebhookRouteRes interface {
	deleteWorkspaceWebhookRouteRes()
}

type DownloadSpeechHistoryItemsRes interface {
	downloadSpeechHistoryItemsRes()
}

type DubRes interface {
	dubRes()
}

type DuplicateAgentRouteRes interface {
	duplicateAgentRouteRes()
}

type EditProjectContentRes interface {
	editProjectContentRes()
}

type EditProjectRes interface {
	editProjectRes()
}

type EditPvcVoiceRes interface {
	editPvcVoiceRes()
}

type EditPvcVoiceSampleRes interface {
	editPvcVoiceSampleRes()
}

type EditServiceAccountAPIKeyRes interface {
	editServiceAccountAPIKeyRes()
}

type EditVoiceRes interface {
	editVoiceRes()
}

type EditVoiceSettingsRes interface {
	editVoiceSettingsRes()
}

type EditWorkspaceWebhookRouteRes interface {
	editWorkspaceWebhookRouteRes()
}

type ForcedAlignmentRes interface {
	forcedAlignmentRes()
}

type GenerateRandomVoiceRes interface {
	generateRandomVoiceRes()
}

type GenerateRes interface {
	generateRes()
}

type GetAgentKnowledgeBaseSizeRes interface {
	getAgentKnowledgeBaseSizeRes()
}

type GetAgentKnowledgeBaseSummariesRouteRes interface {
	getAgentKnowledgeBaseSummariesRouteRes()
}

type GetAgentLinkRouteRes interface {
	getAgentLinkRouteRes()
}

type GetAgentLlmExpectedCostCalculationRes interface {
	getAgentLlmExpectedCostCalculationRes()
}

type GetAgentResponseTestRouteRes interface {
	getAgentResponseTestRouteRes()
}

type GetAgentResponseTestsSummariesRouteRes interface {
	getAgentResponseTestsSummariesRouteRes()
}

type GetAgentsRouteRes interface {
	getAgentsRouteRes()
}

type GetAudioFromSampleRes interface {
	getAudioFromSampleRes()
}

type GetAudioFullFromSpeechHistoryItemRes interface {
	getAudioFullFromSpeechHistoryItemRes()
}

type GetAudioNativeProjectSettingsEndpointRes interface {
	getAudioNativeProjectSettingsEndpointRes()
}

type GetBatchCallRes interface {
	getBatchCallRes()
}

type GetChapterSnapshotEndpointRes interface {
	getChapterSnapshotEndpointRes()
}

type GetChapterSnapshotsRes interface {
	getChapterSnapshotsRes()
}

type GetChaptersRes interface {
	getChaptersRes()
}

type GetConversationAudioRouteRes interface {
	getConversationAudioRouteRes()
}

type GetConversationHistoriesRouteRes interface {
	getConversationHistoriesRouteRes()
}

type GetConversationHistoryRouteRes interface {
	getConversationHistoryRouteRes()
}

type GetConversationSignedLinkRes interface {
	getConversationSignedLinkRes()
}

type GetDashboardSettingsRouteRes interface {
	getDashboardSettingsRouteRes()
}

type GetDocumentationChunkFromKnowledgeBaseRes interface {
	getDocumentationChunkFromKnowledgeBaseRes()
}

type GetDocumentationFromKnowledgeBaseRes interface {
	getDocumentationFromKnowledgeBaseRes()
}

type GetDubbedFileRes interface {
	getDubbedFileRes()
}

type GetDubbedMetadataRes interface {
	getDubbedMetadataRes()
}

type GetDubbedTranscriptFileRes interface {
	getDubbedTranscriptFileRes()
}

type GetDubbingResourceRes interface {
	getDubbingResourceRes()
}

type GetKnowledgeBaseContentRes interface {
	getKnowledgeBaseContentRes()
}

type GetKnowledgeBaseDependentAgentsRes interface {
	getKnowledgeBaseDependentAgentsRes()
}

type GetKnowledgeBaseListRouteRes interface {
	getKnowledgeBaseListRouteRes()
}

type GetLibraryVoicesRes interface {
	getLibraryVoicesRes()
}

type GetLiveCountRes interface {
	getLiveCountRes()
}

type GetLivekitTokenRes interface {
	getLivekitTokenRes()
}

type GetMcpToolConfigOverrideRouteRes interface {
	getMcpToolConfigOverrideRouteRes()
}

type GetModelsRes interface {
	getModelsRes()
}

type GetOrCreateRagIndexesRes interface {
	getOrCreateRagIndexesRes()
}

type GetPhoneNumberRouteRes interface {
	getPhoneNumberRouteRes()
}

type GetProjectSnapshotEndpointRes interface {
	getProjectSnapshotEndpointRes()
}

type GetProjectSnapshotsRes interface {
	getProjectSnapshotsRes()
}

type GetProjectsRes interface {
	getProjectsRes()
}

type GetPronunciationDictionariesMetadataRes interface {
	getPronunciationDictionariesMetadataRes()
}

type GetPronunciationDictionaryMetadataRes interface {
	getPronunciationDictionaryMetadataRes()
}

type GetPronunciationDictionaryVersionPlsRes interface {
	getPronunciationDictionaryVersionPlsRes()
}

type GetPublicLlmExpectedCostCalculationRes interface {
	getPublicLlmExpectedCostCalculationRes()
}

type GetPvcSampleAudioRes interface {
	getPvcSampleAudioRes()
}

type GetPvcSampleSpeakersRes interface {
	getPvcSampleSpeakersRes()
}

type GetPvcSampleVisualWaveformRes interface {
	getPvcSampleVisualWaveformRes()
}

type GetPvcVoiceCaptchaRes interface {
	getPvcVoiceCaptchaRes()
}

type GetRagIndexOverviewRes interface {
	getRagIndexOverviewRes()
}

type GetRagIndexesRes interface {
	getRagIndexesRes()
}

type GetResourceMetadataRes interface {
	getResourceMetadataRes()
}

type GetSecretsRouteRes interface {
	getSecretsRouteRes()
}

type GetServiceAccountAPIKeysRouteRes interface {
	getServiceAccountAPIKeysRouteRes()
}

type GetSettingsRouteRes interface {
	getSettingsRouteRes()
}

type GetSignedURLDeprecatedRes interface {
	getSignedURLDeprecatedRes()
}

type GetSimilarLibraryVoicesRes interface {
	getSimilarLibraryVoicesRes()
}

type GetSimilarVoicesForSpeakerRes interface {
	getSimilarVoicesForSpeakerRes()
}

type GetSingleUseTokenRes interface {
	getSingleUseTokenRes()
}

type GetSpeakerAudioRes interface {
	getSpeakerAudioRes()
}

type GetSpeechHistoryItemByIDRes interface {
	getSpeechHistoryItemByIDRes()
}

type GetSpeechHistoryRes interface {
	getSpeechHistoryRes()
}

type GetTestInvocationRouteRes interface {
	getTestInvocationRouteRes()
}

type GetToolDependentAgentsRouteRes interface {
	getToolDependentAgentsRouteRes()
}

type GetTranscriptByIDRes interface {
	getTranscriptByIDRes()
}

type GetUserInfoRes interface {
	getUserInfoRes()
}

type GetUserVoicesV2Res interface {
	getUserVoicesV2Res()
}

type GetVoiceByIDRes interface {
	getVoiceByIDRes()
}

type GetVoiceSettingsRes interface {
	getVoiceSettingsRes()
}

type GetVoicesRes interface {
	getVoicesRes()
}

type GetWhatsappAccountRes interface {
	getWhatsappAccountRes()
}

type GetWorkspaceBatchCallsRes interface {
	getWorkspaceBatchCallsRes()
}

type GetWorkspaceServiceAccountsRes interface {
	getWorkspaceServiceAccountsRes()
}

type GetWorkspaceWebhooksRouteRes interface {
	getWorkspaceWebhooksRouteRes()
}

type HandleSipTrunkOutboundCallRes interface {
	handleSipTrunkOutboundCallRes()
}

type HandleTwilioOutboundCallRes interface {
	handleTwilioOutboundCallRes()
}

type ImportWhatsappAccountRes interface {
	importWhatsappAccountRes()
}

type InviteUserRes interface {
	inviteUserRes()
}

type InviteUsersBulkRes interface {
	inviteUsersBulkRes()
}

type ListChatResponseTestsRouteRes interface {
	listChatResponseTestsRouteRes()
}

type ListDubsRes interface {
	listDubsRes()
}

type ListMcpServerToolsRouteRes interface {
	listMcpServerToolsRouteRes()
}

type ListPhoneNumbersRouteRes interface {
	listPhoneNumbersRouteRes()
}

type ListTestInvocationsRouteRes interface {
	listTestInvocationsRouteRes()
}

type ListWhatsappAccountsRes interface {
	listWhatsappAccountsRes()
}

type MigrateSegmentsRes interface {
	migrateSegmentsRes()
}

type PatchPronunciationDictionaryRes interface {
	patchPronunciationDictionaryRes()
}

type PostAgentAvatarRouteRes interface {
	postAgentAvatarRouteRes()
}

type PostConversationFeedbackRouteRes interface {
	postConversationFeedbackRouteRes()
}

type RagIndexStatusRes interface {
	ragIndexStatusRes()
}

type RegisterTwilioCallRes interface {
	registerTwilioCallRes()
}

type RemoveMemberRes interface {
	removeMemberRes()
}

type RemoveRulesRes interface {
	removeRulesRes()
}

type RequestPvcManualVerificationRes interface {
	requestPvcManualVerificationRes()
}

type RetryBatchCallRes interface {
	retryBatchCallRes()
}

type RunPvcVoiceTrainingRes interface {
	runPvcVoiceTrainingRes()
}

type SearchGroupsRes interface {
	searchGroupsRes()
}

type SeparateSongStemsRes interface {
	separateSongStemsRes()
}

type ShareResourceEndpointRes interface {
	shareResourceEndpointRes()
}

type SoundGenerationRes interface {
	soundGenerationRes()
}

type SpeechToSpeechFullRes interface {
	speechToSpeechFullRes()
}

type SpeechToSpeechStreamRes interface {
	speechToSpeechStreamRes()
}

type SpeechToTextRes interface {
	speechToTextRes()
}

type StartSpeakerSeparationRes interface {
	startSpeakerSeparationRes()
}

type StreamChapterSnapshotAudioRes interface {
	streamChapterSnapshotAudioRes()
}

type StreamComposeRes interface {
	streamComposeRes()
}

type StreamProjectSnapshotArchiveEndpointRes interface {
	streamProjectSnapshotArchiveEndpointRes()
}

type StreamProjectSnapshotAudioEndpointRes interface {
	streamProjectSnapshotAudioEndpointRes()
}

type TextToDialogueFullWithTimestampsRes interface {
	textToDialogueFullWithTimestampsRes()
}

type TextToDialogueRes interface {
	textToDialogueRes()
}

type TextToDialogueStreamRes interface {
	textToDialogueStreamRes()
}

type TextToDialogueStreamWithTimestampsRes interface {
	textToDialogueStreamWithTimestampsRes()
}

type TextToSpeechFullRes interface {
	textToSpeechFullRes()
}

type TextToSpeechFullWithTimestampsRes interface {
	textToSpeechFullWithTimestampsRes()
}

type TextToSpeechStreamRes interface {
	textToSpeechStreamRes()
}

type TextToSpeechStreamWithTimestampsRes interface {
	textToSpeechStreamWithTimestampsRes()
}

type TextToVoiceDesignRes interface {
	textToVoiceDesignRes()
}

type TextToVoicePreviewStreamRes interface {
	textToVoicePreviewStreamRes()
}

type TextToVoiceRemixRes interface {
	textToVoiceRemixRes()
}

type TextToVoiceRes interface {
	textToVoiceRes()
}

type TranscribeRes interface {
	transcribeRes()
}

type TranslateRes interface {
	translateRes()
}

type UnshareResourceEndpointRes interface {
	unshareResourceEndpointRes()
}

type UpdateAgentResponseTestRouteRes interface {
	updateAgentResponseTestRouteRes()
}

type UpdateDashboardSettingsRouteRes interface {
	updateDashboardSettingsRouteRes()
}

type UpdateDocumentRouteRes interface {
	updateDocumentRouteRes()
}

type UpdatePhoneNumberRouteRes interface {
	updatePhoneNumberRouteRes()
}

type UpdatePronunciationDictionariesRes interface {
	updatePronunciationDictionariesRes()
}

type UpdateSecretRouteRes interface {
	updateSecretRouteRes()
}

type UpdateSegmentLanguageRes interface {
	updateSegmentLanguageRes()
}

type UpdateSettingsRouteRes interface {
	updateSettingsRouteRes()
}

type UpdateSpeakerRes interface {
	updateSpeakerRes()
}

type UpdateWhatsappAccountRes interface {
	updateWhatsappAccountRes()
}

type UpdateWorkspaceMemberRes interface {
	updateWorkspaceMemberRes()
}

type UsageCharactersRes interface {
	usageCharactersRes()
}

type VerifyPvcVoiceCaptchaRes interface {
	verifyPvcVoiceCaptchaRes()
}

type WhatsappOutboundCallRes interface {
	whatsappOutboundCallRes()
}
