// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *AgentSummaryResponseModel) setDefaults() {
	{
		val := bool(false)
		s.Archived.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AsyncConversationMetadata) setDefaults() {
	{
		val := int(0)
		s.RetryCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AudioNativeProjectSettingsResponseModel) setDefaults() {
	{
		val := AudioNativeProjectSettingsResponseModelStatus("ready")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BatchCallDetailedResponse) setDefaults() {
	{
		val := int(0)
		s.RetryCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BatchCallResponse) setDefaults() {
	{
		val := int(0)
		s.RetryCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BatchFailureResponseModel) setDefaults() {
	{
		val := BatchFailureResponseModelStatus("failure")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *BodyAddSamplesToPVCVoiceV1VoicesPvcVoiceIDSamplesPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyAddVoiceV1VoicesAddPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyAudioIsolationStreamV1AudioIsolationStreamPostMultipart) setDefaults() {
	{
		val := BodyAudioIsolationStreamV1AudioIsolationStreamPostMultipartFileFormat("other")
		s.FileFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyAudioIsolationV1AudioIsolationPostMultipart) setDefaults() {
	{
		val := BodyAudioIsolationV1AudioIsolationPostMultipartFileFormat("other")
		s.FileFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyComposeMusicV1MusicPost) setDefaults() {
	{
		val := bool(false)
		s.ForceInstrumental.SetTo(val)
	}
	{
		val := BodyComposeMusicV1MusicPostModelID("music_v1")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(true)
		s.RespectSectionsDurations.SetTo(val)
	}
	{
		val := bool(false)
		s.SignWithC2pa.SetTo(val)
	}
	{
		val := bool(false)
		s.StoreForInpainting.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyComposeMusicWithADetailedResponseV1MusicDetailedPost) setDefaults() {
	{
		val := bool(false)
		s.ForceInstrumental.SetTo(val)
	}
	{
		val := BodyComposeMusicWithADetailedResponseV1MusicDetailedPostModelID("music_v1")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.SignWithC2pa.SetTo(val)
	}
	{
		val := bool(false)
		s.StoreForInpainting.SetTo(val)
	}
	{
		val := bool(false)
		s.WithTimestamps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyCreateForcedAlignmentV1ForcedAlignmentPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.EnabledSpooledFile.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyCreatePronunciationDictionariesV1StudioProjectsProjectIDPronunciationDictionariesPost) setDefaults() {
	{
		val := bool(true)
		s.InvalidateAffectedText.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyCreateStudioProjectV1StudioProjectsPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.AcxVolumeNormalization.SetTo(val)
	}
	{
		val := bool(false)
		s.AutoAssignVoices.SetTo(val)
	}
	{
		val := bool(false)
		s.AutoConvert.SetTo(val)
	}
	{
		val := bool(false)
		s.MatureContent.SetTo(val)
	}
	{
		val := string("standard")
		s.QualityPreset.SetTo(val)
	}
	{
		val := bool(false)
		s.VolumeNormalization.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyCreatesAudioNativeEnabledProjectV1AudioNativePostMultipart) setDefaults() {
	{
		val := bool(false)
		s.AutoConvert.SetTo(val)
	}
	{
		val := int(0)
		s.Sessionization.SetTo(val)
	}
	{
		val := bool(false)
		s.Small.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyDubAVideoOrAnAudioFileV1DubbingPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.DisableVoiceCloning.SetTo(val)
	}
	{
		val := bool(false)
		s.DropBackgroundAudio.SetTo(val)
	}
	{
		val := bool(false)
		s.DubbingStudio.SetTo(val)
	}
	{
		val := bool(false)
		s.HighestResolution.SetTo(val)
	}
	{
		val := BodyDubAVideoOrAnAudioFileV1DubbingPostMultipartMode("automatic")
		s.Mode.SetTo(val)
	}
	{
		val := int(0)
		s.NumSpeakers.SetTo(val)
	}
	{
		val := string("auto")
		s.SourceLang.SetTo(val)
	}
	{
		val := bool(false)
		s.Watermark.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyEditVoiceV1VoicesVoiceIDEditPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyGenerateCompositionPlanV1MusicPlanPost) setDefaults() {
	{
		val := BodyGenerateCompositionPlanV1MusicPlanPostModelID("music_v1")
		s.ModelID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyRegisterATwilioCallAndReturnTwiMLV1ConvaiTwilioRegisterCallPost) setDefaults() {
	{
		val := BodyRegisterATwilioCallAndReturnTwiMLV1ConvaiTwilioRegisterCallPostDirection("inbound")
		s.Direction.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodySoundGenerationV1SoundGenerationPost) setDefaults() {
	{
		val := bool(false)
		s.Loop.SetTo(val)
	}
	{
		val := string("eleven_text_to_sound_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := float64(0.3)
		s.PromptInfluence.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIDStreamPostMultipart) setDefaults() {
	{
		val := BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIDStreamPostMultipartFileFormat("other")
		s.FileFormat.SetTo(val)
	}
	{
		val := string("eleven_english_sts_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodySpeechToSpeechV1SpeechToSpeechVoiceIDPostMultipart) setDefaults() {
	{
		val := BodySpeechToSpeechV1SpeechToSpeechVoiceIDPostMultipartFileFormat("other")
		s.FileFormat.SetTo(val)
	}
	{
		val := string("eleven_english_sts_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodySpeechToTextV1SpeechToTextPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.Diarize.SetTo(val)
	}
	{
		val := BodySpeechToTextV1SpeechToTextPostMultipartFileFormat("other")
		s.FileFormat.SetTo(val)
	}
	{
		val := bool(true)
		s.TagAudioEvents.SetTo(val)
	}
	{
		val := BodySpeechToTextV1SpeechToTextPostMultipartTimestampsGranularity("word")
		s.TimestampsGranularity.SetTo(val)
	}
	{
		val := bool(false)
		s.UseMultiChannel.SetTo(val)
	}
	{
		val := bool(false)
		s.Webhook.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyStemSeparationV1MusicStemSeparationPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.SignWithC2pa.SetTo(val)
	}
	{
		val := BodyStemSeparationV1MusicStemSeparationPostMultipartStemVariationID("six_stems_v1")
		s.StemVariationID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyStreamChapterAudioV1StudioProjectsProjectIDChaptersChapterIDSnapshotsChapterSnapshotIDStreamPost) setDefaults() {
	{
		val := bool(false)
		s.ConvertToMpeg.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyStreamComposedMusicV1MusicStreamPost) setDefaults() {
	{
		val := bool(false)
		s.ForceInstrumental.SetTo(val)
	}
	{
		val := BodyStreamComposedMusicV1MusicStreamPostModelID("music_v1")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.StoreForInpainting.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyStreamStudioProjectAudioV1StudioProjectsProjectIDSnapshotsProjectSnapshotIDStreamPost) setDefaults() {
	{
		val := bool(false)
		s.ConvertToMpeg.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToDialogueFullWithTimestamps) setDefaults() {
	{
		val := BodyTextToDialogueFullWithTimestampsApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_v3")
		s.ModelID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPost) setDefaults() {
	{
		val := BodyTextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPostApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_v3")
		s.ModelID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToDialogueMultiVoiceV1TextToDialoguePost) setDefaults() {
	{
		val := BodyTextToDialogueMultiVoiceV1TextToDialoguePostApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_v3")
		s.ModelID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToDialogueStreamWithTimestamps) setDefaults() {
	{
		val := BodyTextToDialogueStreamWithTimestampsApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_v3")
		s.ModelID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToSpeechFull) setDefaults() {
	{
		val := bool(false)
		s.ApplyLanguageTextNormalization.SetTo(val)
	}
	{
		val := BodyTextToSpeechFullApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_multilingual_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.UsePvcAsIvc.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToSpeechFullWithTimestamps) setDefaults() {
	{
		val := bool(false)
		s.ApplyLanguageTextNormalization.SetTo(val)
	}
	{
		val := BodyTextToSpeechFullWithTimestampsApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_multilingual_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.UsePvcAsIvc.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToSpeechStream) setDefaults() {
	{
		val := bool(false)
		s.ApplyLanguageTextNormalization.SetTo(val)
	}
	{
		val := BodyTextToSpeechStreamApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_multilingual_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.UsePvcAsIvc.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyTextToSpeechStreamWithTimestamps) setDefaults() {
	{
		val := bool(false)
		s.ApplyLanguageTextNormalization.SetTo(val)
	}
	{
		val := BodyTextToSpeechStreamWithTimestampsApplyTextNormalization("auto")
		s.ApplyTextNormalization.SetTo(val)
	}
	{
		val := string("eleven_multilingual_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.UsePvcAsIvc.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyUpdateAudioNativeProjectContentV1AudioNativeProjectIDContentPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.AutoConvert.SetTo(val)
	}
	{
		val := bool(false)
		s.AutoPublish.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyUpdatePVCVoiceSampleV1VoicesPvcVoiceIDSamplesSampleIDPost) setDefaults() {
	{
		val := bool(false)
		s.RemoveBackgroundNoise.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyUpdateStudioProjectContentV1StudioProjectsProjectIDContentPostMultipart) setDefaults() {
	{
		val := bool(false)
		s.AutoConvert.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BodyUpdateStudioProjectV1StudioProjectsProjectIDPost) setDefaults() {
	{
		val := bool(false)
		s.VolumeNormalization.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CaptionStyleTemplateModel) setDefaults() {
	{
		val := bool(false)
		s.RequiresHighFps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationChargingCommonModel) setDefaults() {
	{
		val := bool(false)
		s.DevDiscount.SetTo(val)
	}
	{
		val := float64(0)
		s.FreeLlmDollarsConsumed.SetTo(val)
	}
	{
		val := float64(0)
		s.FreeMinutesConsumed.SetTo(val)
	}
	{
		val := bool(false)
		s.IsBurst.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationDeletionSettings) setDefaults() {
	{
		val := bool(false)
		s.DeleteAudio.SetTo(val)
	}
	{
		val := bool(false)
		s.DeleteTranscriptAndPii.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryElevenAssistantCommonModel) setDefaults() {
	{
		val := bool(false)
		s.IsElevenAssistant.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryFeedbackCommonModel) setDefaults() {
	{
		val := int(0)
		s.Dislikes.SetTo(val)
	}
	{
		val := int(0)
		s.Likes.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryMetadataCommonModel) setDefaults() {
	{
		val := AgentDefinitionSource("unknown")
		s.AgentCreatedFrom.SetTo(val)
	}
	{
		val := AgentDefinitionSource("unknown")
		s.AgentLastUpdatedFrom.SetTo(val)
	}
	{
		val := AuthorizationMethod("public")
		s.AuthorizationMethod.SetTo(val)
	}
	{
		val := ConversationInitiationSource("unknown")
		s.ConversationInitiationSource.SetTo(val)
	}
	{
		val := string("")
		s.TerminationReason.SetTo(val)
	}
	{
		val := bool(false)
		s.TextOnly.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptApiIntegrationWebhookToolsResultCommonModel) setDefaults() {
	{
		val := float64(0)
		s.ToolLatencySecs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptCommonModelInput) setDefaults() {
	{
		val := bool(false)
		s.Interrupted.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptCommonModelOutput) setDefaults() {
	{
		val := bool(false)
		s.Interrupted.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptOtherToolsResultCommonModel) setDefaults() {
	{
		val := float64(0)
		s.ToolLatencySecs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptSystemToolResultCommonModel) setDefaults() {
	{
		val := float64(0)
		s.ToolLatencySecs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptToolCallApiIntegrationWebhookDetails) setDefaults() {
	{
		val := ConversationHistoryTranscriptToolCallApiIntegrationWebhookDetailsType("api_integration_webhook")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptToolCallClientDetails) setDefaults() {
	{
		val := ConversationHistoryTranscriptToolCallClientDetailsType("client")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptToolCallMCPDetails) setDefaults() {
	{
		val := string("")
		s.McpToolDescription.SetTo(val)
	}
	{
		val := string("")
		s.McpToolName.SetTo(val)
	}
	{
		val := bool(false)
		s.RequiresApproval.SetTo(val)
	}
	{
		val := ConversationHistoryTranscriptToolCallMCPDetailsType("mcp")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptToolCallWebhookDetails) setDefaults() {
	{
		val := ConversationHistoryTranscriptToolCallWebhookDetailsType("webhook")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptWorkflowToolsResultCommonModelInput) setDefaults() {
	{
		val := float64(0)
		s.ToolLatencySecs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationHistoryTranscriptWorkflowToolsResultCommonModelOutput) setDefaults() {
	{
		val := float64(0)
		s.ToolLatencySecs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationInitiationSourceInfo) setDefaults() {
	{
		val := ConversationInitiationSource("unknown")
		s.Source.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationTokenDBModel) setDefaults() {
	{
		val := ConversationTokenPurpose("signed_url")
		s.Purpose.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DashboardCallSuccessChartModel) setDefaults() {
	{
		val := DashboardCallSuccessChartModelType("call_success")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DashboardCriteriaChartModel) setDefaults() {
	{
		val := DashboardCriteriaChartModelType("criteria")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DashboardDataCollectionChartModel) setDefaults() {
	{
		val := DashboardDataCollectionChartModelType("data_collection")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DefaultConversationInitiationTrigger) setDefaults() {
	{
		val := DefaultConversationInitiationTriggerTriggerType("default")
		s.TriggerType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DependentAvailableAgentIdentifier) setDefaults() {
	{
		val := DependentAvailableAgentIdentifierType("available")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DependentAvailableToolIdentifier) setDefaults() {
	{
		val := DependentAvailableToolIdentifierType("available")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DependentUnknownAgentIdentifier) setDefaults() {
	{
		val := DependentUnknownAgentIdentifierType("unknown")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DependentUnknownToolIdentifier) setDefaults() {
	{
		val := DependentUnknownToolIdentifierType("unknown")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DocxExportOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DubbingMetadataResponse) setDefaults() {
	{
		val := bool(false)
		s.Editable.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DubbingTranscriptCharacter) setDefaults() {
	{
		val := float64(0)
		s.EndS.SetTo(val)
	}
	{
		val := float64(0)
		s.StartS.SetTo(val)
	}
	{
		val := string("")
		s.Text.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DubbingTranscriptUtterance) setDefaults() {
	{
		val := float64(0)
		s.EndS.SetTo(val)
	}
	{
		val := string("unknown")
		s.SpeakerID.SetTo(val)
	}
	{
		val := float64(0)
		s.StartS.SetTo(val)
	}
	{
		val := string("")
		s.Text.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DubbingTranscriptWord) setDefaults() {
	{
		val := float64(0)
		s.EndS.SetTo(val)
	}
	{
		val := float64(0)
		s.StartS.SetTo(val)
	}
	{
		val := string("")
		s.Text.SetTo(val)
	}
	{
		val := string("unknown")
		s.WordType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DynamicVariableAssignment) setDefaults() {
	{
		val := DynamicVariableAssignmentSource("response")
		s.Source.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EndCallToolResultModel) setDefaults() {
	{
		val := EndCallToolResultModelResultType("end_call_success")
		s.ResultType.SetTo(val)
	}
	{
		val := EndCallToolResultModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FeatureStatusCommonModel) setDefaults() {
	{
		val := bool(false)
		s.Enabled.SetTo(val)
	}
	{
		val := bool(false)
		s.Used.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FeaturesUsageCommonModel) setDefaults() {
	{
		val := bool(false)
		s.IsLivekit.SetTo(val)
	}
	{
		val := bool(false)
		s.PiiZrmAgent.SetTo(val)
	}
	{
		val := bool(false)
		s.PiiZrmWorkspace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FeedbackResponseModel) setDefaults() {
	{
		val := string("not_reviewed")
		s.ReviewStatus.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetConvAISettingsResponseModel) setDefaults() {
	{
		val := bool(false)
		s.CanUseMcpServers.SetTo(val)
	}
	{
		val := LivekitStackType("standard")
		s.DefaultLivekitStack.SetTo(val)
	}
	{
		val := int(10)
		s.RagRetentionPeriodDays.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetOrCreateRAGIndexRequestModel) setDefaults() {
	{
		val := EmbeddingModelEnum("e5_mistral_7b_instruct")
		s.Model = val
	}
}

// setDefaults set default value of fields.
func (s *GetPhoneNumberInboundSIPTrunkConfigResponseModel) setDefaults() {
	{
		val := SIPMediaEncryptionEnum("allowed")
		s.MediaEncryption = val
	}
}

// setDefaults set default value of fields.
func (s *GetPhoneNumberOutboundSIPTrunkConfigResponseModel) setDefaults() {
	{
		val := bool(false)
		s.HasOutboundTrunk.SetTo(val)
	}
	{
		val := SIPMediaEncryptionEnum("allowed")
		s.MediaEncryption = val
	}
	{
		val := SIPTrunkTransportEnum("auto")
		s.Transport = val
	}
}

// setDefaults set default value of fields.
func (s *GetPhoneNumberSIPTrunkResponseModel) setDefaults() {
	{
		val := LivekitStackType("standard")
		s.LivekitStack = val
	}
	{
		val := GetPhoneNumberSIPTrunkResponseModelProvider("sip_trunk")
		s.Provider.SetTo(val)
	}
	{
		val := bool(true)
		s.SupportsInbound.SetTo(val)
	}
	{
		val := bool(true)
		s.SupportsOutbound.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetPhoneNumberTwilioResponseModel) setDefaults() {
	{
		val := GetPhoneNumberTwilioResponseModelProvider("twilio")
		s.Provider.SetTo(val)
	}
	{
		val := bool(true)
		s.SupportsInbound.SetTo(val)
	}
	{
		val := bool(true)
		s.SupportsOutbound.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *HtmlExportOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *InboundSIPTrunkConfigRequestModel) setDefaults() {
	{
		val := SIPMediaEncryptionEnum("allowed")
		s.MediaEncryption.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *KnowledgeBaseSummaryBatchSuccessfulResponseModel) setDefaults() {
	{
		val := KnowledgeBaseSummaryBatchSuccessfulResponseModelStatus("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *LLMTokensCategoryUsage) setDefaults() {
	{
		val := float64(0)
		s.Price.SetTo(val)
	}
	{
		val := int(0)
		s.Tokens.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *LLMUsageCalculatorLLMResponseModel) setDefaults() {
	{
		val := LLM("gemini-2.5-flash")
		s.Llm = val
	}
}

// setDefaults set default value of fields.
func (s *LanguageDetectionToolResultModel) setDefaults() {
	{
		val := LanguageDetectionToolResultModelResultType("language_detection_success")
		s.ResultType.SetTo(val)
	}
	{
		val := LanguageDetectionToolResultModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *LiteralJsonSchemaProperty) setDefaults() {
	{
		val := string("")
		s.Description.SetTo(val)
	}
	{
		val := string("")
		s.DynamicVariable.SetTo(val)
	}
	{
		val := bool(false)
		s.IsSystemProvided.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MCPToolConfigOverride) setDefaults() {
	{
		val := ToolExecutionMode("immediate")
		s.ExecutionMode.SetTo(val)
	}
	{
		val := ToolCallSoundBehavior("auto")
		s.ToolCallSoundBehavior.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelSettingsResponseModel) setDefaults() {
	{
		val := float64(0.5)
		s.Stability.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OutboundSIPTrunkConfigRequestModel) setDefaults() {
	{
		val := SIPMediaEncryptionEnum("allowed")
		s.MediaEncryption.SetTo(val)
	}
	{
		val := SIPTrunkTransportEnum("auto")
		s.Transport.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PatchConvAISettingsRequest) setDefaults() {
	{
		val := bool(false)
		s.CanUseMcpServers.SetTo(val)
	}
	{
		val := LivekitStackType("standard")
		s.DefaultLivekitStack.SetTo(val)
	}
	{
		val := int(10)
		s.RagRetentionPeriodDays.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PdfExportOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PlayDTMFResultErrorModel) setDefaults() {
	{
		val := PlayDTMFResultErrorModelResultType("play_dtmf_error")
		s.ResultType.SetTo(val)
	}
	{
		val := PlayDTMFResultErrorModelStatus("error")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PlayDTMFResultSuccessModel) setDefaults() {
	{
		val := PlayDTMFResultSuccessModelResultType("play_dtmf_success")
		s.ResultType.SetTo(val)
	}
	{
		val := PlayDTMFResultSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ProjectResponseModel) setDefaults() {
	{
		val := bool(true)
		s.CaptionsEnabled.SetTo(val)
	}
	{
		val := bool(true)
		s.ChaptersEnabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptAgentAPIModelOverride) setDefaults() {
	{
		val := LLM("gemini-2.5-flash")
		s.Llm.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RAGDocumentIndexResponseModel) setDefaults() {
	{
		val := EmbeddingModelEnum("e5_mistral_7b_instruct")
		s.Model = val
	}
}

// setDefaults set default value of fields.
func (s *RAGIndexBatchSuccessfulResponseModel) setDefaults() {
	{
		val := RAGIndexBatchSuccessfulResponseModelStatus("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *RAGIndexOverviewEmbeddingModelResponseModel) setDefaults() {
	{
		val := EmbeddingModelEnum("e5_mistral_7b_instruct")
		s.Model = val
	}
}

// setDefaults set default value of fields.
func (s *RAGIndexRequestModel) setDefaults() {
	{
		val := EmbeddingModelEnum("e5_mistral_7b_instruct")
		s.Model = val
	}
}

// setDefaults set default value of fields.
func (s *RagRetrievalInfo) setDefaults() {
	{
		val := EmbeddingModelEnum("e5_mistral_7b_instruct")
		s.EmbeddingModel = val
	}
}

// setDefaults set default value of fields.
func (s *SegmentedJsonExportOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SkipTurnToolResponseModel) setDefaults() {
	{
		val := SkipTurnToolResponseModelResultType("skip_turn_success")
		s.ResultType.SetTo(val)
	}
	{
		val := SkipTurnToolResponseModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SrtExportOptions) setDefaults() {
	{
		val := bool(false)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
	{
		val := int(42)
		s.MaxCharactersPerLine.SetTo(val)
	}
	{
		val := int(84)
		s.MaxSegmentChars.SetTo(val)
	}
	{
		val := float64(4)
		s.MaxSegmentDurationS.SetTo(val)
	}
	{
		val := float64(0.8)
		s.SegmentOnSilenceLongerThanS.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TestConditionRationaleCommonModel) setDefaults() {
	{
		val := string("")
		s.Summary.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TestRunMetadata) setDefaults() {
	{
		val := TestRunMetadataTestType("llm")
		s.TestType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TestToolResultModel) setDefaults() {
	{
		val := string("Skipping tool call in test mode")
		s.Reason.SetTo(val)
	}
	{
		val := TestToolResultModelResultType("testing_tool_result")
		s.ResultType.SetTo(val)
	}
	{
		val := TestToolResultModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TestsFeatureUsageCommonModel) setDefaults() {
	{
		val := bool(false)
		s.Enabled.SetTo(val)
	}
	{
		val := bool(false)
		s.TestsRanAfterLastModification.SetTo(val)
	}
	{
		val := bool(false)
		s.TestsRanInLast7Days.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToAgentToolResultErrorModel) setDefaults() {
	{
		val := TransferToAgentToolResultErrorModelResultType("transfer_to_agent_error")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToAgentToolResultErrorModelStatus("error")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToAgentToolResultSuccessModel) setDefaults() {
	{
		val := int(0)
		s.DelayMs.SetTo(val)
	}
	{
		val := bool(false)
		s.EnableTransferredAgentFirstMessage.SetTo(val)
	}
	{
		val := TransferToAgentToolResultSuccessModelResultType("transfer_to_agent_success")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToAgentToolResultSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToNumberResultErrorModel) setDefaults() {
	{
		val := TransferToNumberResultErrorModelResultType("transfer_to_number_error")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToNumberResultErrorModelStatus("error")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToNumberResultSipSuccessModel) setDefaults() {
	{
		val := TransferToNumberResultSipSuccessModelResultType("transfer_to_number_sip_success")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToNumberResultSipSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransferToNumberResultTwilioSuccessModel) setDefaults() {
	{
		val := TransferToNumberResultTwilioSuccessModelResultType("transfer_to_number_twilio_success")
		s.ResultType.SetTo(val)
	}
	{
		val := TransferToNumberResultTwilioSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TxtExportOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeSpeakers.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeTimestamps.SetTo(val)
	}
	{
		val := int(100)
		s.MaxCharactersPerLine.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UnitTestRunResponseModel) setDefaults() {
	{
		val := string("Unknown Test")
		s.TestName.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UnitTestToolCallEvaluationModelInput) setDefaults() {
	{
		val := bool(false)
		s.VerifyAbsence.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UnitTestToolCallEvaluationModelOutput) setDefaults() {
	{
		val := bool(false)
		s.VerifyAbsence.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdatePhoneNumberRequest) setDefaults() {
	{
		val := LivekitStackType("standard")
		s.LivekitStack.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UserResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsAPIKeyHashed.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoiceDesignRequestModel) setDefaults() {
	{
		val := bool(false)
		s.AutoGenerateText.SetTo(val)
	}
	{
		val := float64(5)
		s.GuidanceScale.SetTo(val)
	}
	{
		val := float64(0.5)
		s.Loudness.SetTo(val)
	}
	{
		val := VoiceDesignRequestModelModelID("eleven_multilingual_ttv_v2")
		s.ModelID.SetTo(val)
	}
	{
		val := bool(false)
		s.ShouldEnhance.SetTo(val)
	}
	{
		val := bool(false)
		s.StreamPreviews.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoiceMailDetectionResultSuccessModel) setDefaults() {
	{
		val := VoiceMailDetectionResultSuccessModelResultType("voicemail_detection_success")
		s.ResultType.SetTo(val)
	}
	{
		val := VoiceMailDetectionResultSuccessModelStatus("success")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoicePreviewsRequestModel) setDefaults() {
	{
		val := bool(false)
		s.AutoGenerateText.SetTo(val)
	}
	{
		val := float64(5)
		s.GuidanceScale.SetTo(val)
	}
	{
		val := float64(0.5)
		s.Loudness.SetTo(val)
	}
	{
		val := float64(0.9)
		s.Quality.SetTo(val)
	}
	{
		val := bool(false)
		s.ShouldEnhance.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoiceRemixRequestModel) setDefaults() {
	{
		val := bool(false)
		s.AutoGenerateText.SetTo(val)
	}
	{
		val := float64(2)
		s.GuidanceScale.SetTo(val)
	}
	{
		val := float64(0.5)
		s.Loudness.SetTo(val)
	}
	{
		val := bool(false)
		s.StreamPreviews.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoiceResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsLegacy.SetTo(val)
	}
	{
		val := bool(false)
		s.IsMixed.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *VoiceSettingsResponseModel) setDefaults() {
	{
		val := float64(0.75)
		s.SimilarityBoost.SetTo(val)
	}
	{
		val := float64(1)
		s.Speed.SetTo(val)
	}
	{
		val := float64(0.5)
		s.Stability.SetTo(val)
	}
	{
		val := float64(0)
		s.Style.SetTo(val)
	}
	{
		val := bool(true)
		s.UseSpeakerBoost.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WhatsAppConversationInfo) setDefaults() {
	{
		val := WhatsAppConversationInfoDirection("unknown")
		s.Direction.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkflowFeaturesUsageCommonModel) setDefaults() {
	{
		val := bool(false)
		s.Enabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkflowToolEdgeStepModel) setDefaults() {
	{
		val := WorkflowToolEdgeStepModelType("edge")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkflowToolMaxIterationsExceededStepModel) setDefaults() {
	{
		val := WorkflowToolMaxIterationsExceededStepModelType("max_iterations_exceeded")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkflowToolNestedToolsStepModelInput) setDefaults() {
	{
		val := WorkflowToolNestedToolsStepModelInputType("nested_tools")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkflowToolNestedToolsStepModelOutput) setDefaults() {
	{
		val := WorkflowToolNestedToolsStepModelOutputType("nested_tools")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkspaceApiKeyResponseModel) setDefaults() {
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkspaceBatchCallsResponse) setDefaults() {
	{
		val := bool(false)
		s.HasMore.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ZendeskConversationInitiationTrigger) setDefaults() {
	{
		val := ZendeskConversationInitiationTriggerTriggerType("zendesk")
		s.TriggerType.SetTo(val)
	}
}
